window.TRUSELV_CONFIG = {
  "siteUrl": "https://truselv.co.uk",
  "email": "support@truselv.co.uk",
  "phone": "+44 7920 693839",
  "address": "We Are Super, High St, Weston-super-Mare BS23 1HL, United Kingdom",
  "legalName": "TRUSELV LTD",
  "companyNumber": "17224419",
  "registeredOffice": "9 Moorland Road, Weston-super-Mare, United Kingdom, BS23 4HW",
  "vatNumber": "",
  "salesReady": true,
  "tessUnitPrice": 119,
  "vatStatement": "£119 per tablet. No VAT is charged.",
  "deliveryStatement": "UK delivery: standard delivery is free (3–5 working days). Next working day delivery is £4.99 per order for orders placed before 6pm UK time. Choose your delivery option at checkout.",
  "bundleStatement": "Each TESS bundle includes an 11-inch Android 15 tablet, keyboard, mouse, protective case, stylus pen, headphones and charger, plus lifetime support for the TESS app.",
  "appStoreUrl": "",
  "playStoreUrl": "",
  "inquiryEndpoint": "",
  "checkoutEndpoint": "",
  "orderStatusEndpoint": ""
};
