"""Public policy and trust content. Capabilities are not certifications."""
from html import escape as E

def build_policies(page,hero,cta,config,date):
    email=config['email']
    contact=f'<a href="mailto:{email}">{email}</a>'
    gov='https://www.gov.uk/online-and-distance-selling-for-businesses'
    returns='https://www.gov.uk/accepting-returns-and-giving-refunds'
    ico='https://ico.org.uk/for-the-public/'
    def document(file,title,intro,sections,extra=''):
        nav='<aside class="document-nav" aria-label="On this page"><h2>On this page</h2>'+''.join(f'<a href="#section-{i}">{t}</a>' for i,(t,_) in enumerate(sections))+'</aside>'
        body=hero('Trust & legal',title,intro,f'<div class="document-meta"><span>Updated {date}</span><span>Version 1.0</span></div>')
        body+='<section class="section"><div class="container document-layout">'+nav+'<article class="document-body">'+extra+''.join(f'<section id="section-{i}"><h2>{t}</h2>{copy}</section>' for i,(t,copy) in enumerate(sections))+'</article></div></section>'
        page(file,title,intro,body)

    document('privacy.html','Website privacy notice','How information is handled when you browse this website, enquire about a product or ask for help.',[
        ('Who this notice covers',f'<p>This notice covers the TruSelv marketing website and product, demo, support and order enquiries sent to TruSelv. Contact {contact} or write to {E(config["address"])} for privacy questions. See <a href="legal.html">company information</a> for the website operator and contracting details.</p><p>It does not describe patient-data processing inside Bedbord or TESS. A care organisation using a product must provide its own relevant privacy information. Product-specific notices and agreements must be reviewed before deployment.</p>'),
        ('Information you provide','<p>Enquiries may include your name, email, organisation, role, product of interest, postcode or ODS code, referral source and the message you choose to write. An order enquiry also includes the requested quantity and delivery postcode. Do not send patient records, health details, identity documents or payment-card information through these forms.</p><p>Form information remains in the current page’s memory until you choose to send it. It is not saved to browser storage. In email mode, the site prepares a message for your email application; you choose whether to send it. Copying a message places it on your clipboard at your request.</p>'),
        ('Browsing and providers','<p>The website serves its own fonts, images and videos and does not include advertising pixels, analytics trackers or embedded third-party video players. Hosting and network providers can receive ordinary request information, such as IP address, requested URL, user agent and time, to deliver and secure the site.</p><p>The current static site is intended for GitHub Pages hosting. Read <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</a> for provider information. If the site is served through another provider, that deployment’s hosting arrangements must be reflected in this notice.</p><p>Your email service processes messages you send. TruSelv’s email and, where enabled, form delivery providers process enquiries to deliver them to us. Enabled enquiry forms use Resend to deliver your message and reply address to support@truselv.co.uk. Delivery addresses are entered manually and passed to Stripe when opening secure checkout. Secure checkout embeds Stripe, which processes payment and delivery details; TruSelv does not receive card numbers. Read the <a href="https://resend.com/legal/privacy-policy">Resend privacy notice</a> and <a href="https://stripe.com/privacy">Stripe privacy notice</a>.</p>'),
        ('Why we use it','<ul><li><strong>Product and demo enquiries:</strong> to respond and arrange a conversation. Our basis is legitimate interests in handling business enquiries, or steps at your request before entering a contract where applicable.</li><li><strong>Orders and support:</strong> to discuss or fulfil the relevant contract, resolve issues and maintain appropriate business records.</li><li><strong>Security and service operation:</strong> legitimate interests in delivering and protecting the website and communications.</li><li><strong>Legal requirements:</strong> to meet applicable accounting, tax, consumer or other legal obligations.</li></ul><p>Acknowledging this notice is not consent to marketing. These forms do not subscribe you to a marketing list. We do not use these enquiries for automated decisions with legal or similarly significant effects.</p>'),
        ('Sharing and international processing','<p>Information is shared only as needed with people handling the enquiry, service providers supporting delivery, or advisers and authorities where required by law or to establish or defend legal rights. We do not sell enquiry information for advertising.</p><p>Provider infrastructure may process information outside the UK. Where a restricted international transfer is involved, an appropriate transfer mechanism must be in place. Contact us for information about the recipients and safeguards relevant to your enquiry. Do not infer UK-only hosting or a specific product data location from this marketing site.</p>'),
        ('How long information is kept','<p>Enquiry information is kept while the conversation or support issue is active and for the period needed to handle follow-up, complaints or relevant legal obligations. Order and accounting records may need to be retained for statutory periods. Information that is no longer needed should be deleted or anonymised.</p><p>Retention is determined by the type of enquiry, any resulting contract and applicable obligations. Ask us for the retention period or criteria that apply to your information. The marketing website itself does not store a persistent copy of form data or a shopping basket in your browser.</p>'),
        ('Your rights',f'<p>Depending on the circumstances, you can request access, correction, erasure, restriction or portability of your personal information, or object to processing based on legitimate interests. If processing relies on consent, you can withdraw it without affecting earlier lawful processing.</p><p>Send a request to {contact}. We may need proportionate information to verify identity. Rights have conditions and exceptions; we will explain any that apply. You can also raise a concern with the <a href="{ico}">Information Commissioner’s Office</a>.</p>'),
        ('Changes and contact',f'<p>This version is dated {date}. Review the notice when providing new information, as services and providers may change. Product-data questions should also be directed to the care organisation responsible for your care.</p><p>Contact: {contact}. A <a href="downloads/website-privacy-notice.pdf">PDF copy of this notice</a> is available.</p>')
    ])
    document('cookies.html','Cookies & local storage','A straightforward explanation of the technology used by this website.',[
        ('What this website uses','<p>The marketing website code does not set cookies, use localStorage or sessionStorage, or install analytics, advertising or social media tracking scripts. When you choose secure checkout, Stripe’s embedded payment form loads and may use cookies and similar technology necessary for payment and fraud prevention. See <a href="https://stripe.com/legal/cookies-policy">Stripe’s cookie policy</a>. It does not use third-party video embeds. Its fonts, images and videos are served as site assets.</p><p>A temporary basket quantity, calculator values and form entries are held in the current page’s memory. Reloading or leaving the page clears them. Browsers may independently retain autofill details under your own browser settings.</p>'),
        ('Cookie preferences','<p>There are no optional tracking categories to accept or reject in this version. The Cookie preferences control in the footer explains this. It does not write a consent cookie because there are no optional tracking services to activate.</p><p>If optional tracking is introduced later, this policy and any necessary controls must be updated before it runs.</p>'),
        ('Other websites and services','<p>Opening an email application or app-store page takes you into another service. Payment checkout embeds Stripe within the shop page. That service may use its own storage, cookies and privacy controls. Your browser also caches downloaded resources to improve performance.</p><p>Hosting infrastructure may process connection information to deliver and secure the site. See the <a href="privacy.html">privacy notice</a> for more detail.</p>'),
        ('Your browser controls',f'<p>You can control cookies, saved form data and cache through your browser. The information and product pages remain readable without optional storage. Contact {contact} if you notice a service that does not match this description.</p><p>Learn more from the <a href="https://ico.org.uk/for-the-public/online/cookies/">ICO’s explanation of cookies</a>.</p>')
    ])
    document('terms.html','Website terms','The terms for browsing and using the TruSelv marketing website.',[
        ('Using this site','<p>This website introduces TruSelv, Bedbord and TESS and provides routes to product enquiries and support. Use it lawfully and with respect for other people’s privacy. If you cannot use the site, contact us for an alternative route.</p><p>A demo request is a request for contact. It does not confirm a meeting, deployment, purchase, delivery date or support service level. An order enquiry is not a contract of sale.</p>'),
        ('Product information','<p>Product descriptions explain intended uses and areas to explore during discovery. The applicable specification, app release, included accessories, compatibility, pricing and terms must be confirmed before purchase or deployment. Images and films may be illustrative or synthetic and are not evidence of a clinical deployment, customer endorsement or final production bundle.</p><p>Bedbord is presented as a bedside communication display and TESS as an engagement experience. Content on this website is not medical advice or a substitute for professional assessment, clinical records or emergency services.</p>'),
        ('Resources and estimates','<p>Product briefs and planning checklists support discussion; they are not certifications, safety cases or release-specific instructions. The calculator uses user-entered assumptions to model time and value. It does not guarantee savings, clinical benefits or environmental improvements.</p><p>Care organisations remain responsible for their local assessment, clinical decisions, procurement approvals and deployment responsibilities.</p>'),
        ('Intellectual property','<p>TruSelv branding, site design and authored content are protected by applicable intellectual-property rights. You may read, download and share our published PDFs internally for product evaluation, with attribution and without altering their meaning. Do not imply an endorsement or use our brand as your own.</p><p>Third-party marks remain the property of their owners. Local fonts are distributed under their supplied SIL Open Font Licences. Other uses of site material require permission unless permitted by law.</p>'),
        ('Availability and external links','<p>We aim to keep information useful and accurate, but website access and content may change or be interrupted. We cannot guarantee uninterrupted availability. External links are provided for convenience and reference; their operators control their content and services.</p><p>Do not attempt to disrupt the website, bypass security, introduce malicious software or collect information about other visitors.</p>'),
        ('Liability and applicable law','<p>Nothing in these terms excludes liability that cannot lawfully be excluded, including for fraud or death or personal injury caused by negligence, or limits mandatory consumer rights. Product purchases are subject to the applicable sale agreement and statutory rights.</p><p>These website terms are governed by the law of England and Wales. This does not take away mandatory consumer protections or rights to bring proceedings in a court available under applicable law.</p>'),
        ('Contact and updates',f'<p>Contact {contact} with website questions. The date at the top identifies this version. Separate <a href="sales-terms.html">sales terms</a>, the <a href="privacy.html">privacy notice</a> and the <a href="acceptable-use.html">acceptable use guidance</a> explain other relevant matters.</p>')
    ])
    document('sales-terms.html','TESS sales & enquiry terms','What the TESS offer means, how an enquiry works and what must be agreed before a purchase.',[
        ('Enquiries and contract formation','<p>The current shopping journey prepares an order enquiry unless an identified payment checkout is available. An enquiry, automated acknowledgement or review screen does not accept an order, reserve stock or create a subscription.</p><p>Before you pay, the seller must provide its legal identity and address, the exact goods and services, full price and taxes, delivery arrangements, applicable cancellation information and the terms governing acceptance. Your written order confirmation will identify when the sale contract is formed. Keep the terms, quote and receipt.</p>'),
        ('The TESS offer',f'<p>The advertised base offer is £{config["tessUnitPrice"]} for one TESS tablet. {E(config["bundleStatement"])}</p><p>Photography is illustrative. It does not establish a contractual hardware specification, accessory list, colour, packaging or stock availability. The written specification supplied before payment takes precedence over an illustrative image.</p>'),
        ('Price, taxes and delivery',f'<p>{E(config["vatStatement"])} {E(config["deliveryStatement"])}</p><p>The complete payable price, including applicable taxes and compulsory charges, must be disclosed before the customer commits to buy. Standard UK delivery is free; next working day delivery costs £4.99 per order. Quantity totals on the enquiry page show the product subtotal only.</p><p>Payment methods and the proposed delivery period will be stated in the offer or checkout. Unless a different delivery period is agreed, consumer goods must normally be delivered within 30 days of contract formation.</p>'),
        ('Apps and digital content','<p>The activation date, supported devices, account rules, included features, update arrangements and service availability must be specified before purchase. A free app download is not a promise that all features are free.</p><p>No consent to immediate digital supply or waiver of cancellation rights is collected by this website enquiry. If immediate supply affects cancellation rights, the applicable information and any required express consent and acknowledgement must be provided separately before supply starts. Hardware cancellation rights must not be treated as automatically lost when an app is opened.</p>'),
        ('Suitability and use','<p>Check the device and current app requirements for the intended user and setting. Some activities may need internet connectivity, third-party accounts or separate licences. Shared organisational use, safeguarding, device management and hygiene need local assessment.</p><p>TESS is not offered here as diagnosis, treatment, emergency monitoring or a replacement for human support. Follow the supplied device instructions and applicable organisational policies.</p>'),
        ('Cancellation, faults and returns','<p>Eligible UK consumers purchasing at a distance normally have 14 days after receiving goods to notify cancellation, then another 14 days to send them back. Separate rights apply to faulty, misdescribed or unfit goods, and to digital content or services. Mandatory rights are not replaced by any manufacturer warranty.</p><p>See <a href="returns.html">delivery & returns</a> for details and the <a href="downloads/cancellation-form.pdf">cancellation form</a>. Business purchases and negotiated organisational contracts may have different cancellation terms; those must be agreed in writing.</p>'),
        ('Help and complaints',f'<p>Contact {contact} with your order reference and a short description of the issue. Do not send card details or sensitive care information. We will discuss the applicable resolution route and any further information needed.</p><p>These terms do not exclude statutory rights or liability that cannot lawfully be excluded. The governing law and seller’s jurisdiction will be identified in the final contract, subject to mandatory consumer protections.</p><p>Reference: <a href="{gov}">GOV.UK distance selling guidance</a>.</p>')
    ])
    document('returns.html','Delivery, cancellation & returns','Practical information for TESS orders and a clear way to ask for help.',[
        ('Before delivery','<p>Standard UK delivery is free and takes 3–5 working days. Next working day delivery is available for £4.99 per order for orders placed before 6pm UK time. Online checkout accepts UK delivery addresses only. Choose your delivery option at checkout. For consumer goods, delivery is normally due within 30 days unless you agree a different period.</p><p>Inspect the package when it arrives and contact us if the item is damaged, missing or incorrect. Keep your order confirmation. Please do not publish order documents containing personal information.</p>'),
        ('Changing your mind','<p>For an eligible UK consumer distance purchase of goods, tell us within 14 days after receipt if you want to cancel. You then normally have a further 14 days to send the goods back. You do not have to give a reason.</p><p>You may inspect goods as you would in a shop. A lawful deduction may apply for diminished value caused by handling beyond what is needed to establish their nature, characteristics and functioning. Original packaging is helpful but is not a blanket condition for exercising statutory rights.</p><p>We do not apply a general “opened technology cannot be returned” exclusion. Any lawful exception relevant to a specific item must be explained before purchase.</p>'),
        ('How to cancel or return',f'<ol><li>Email {contact} with your order reference, name, the items concerned and a clear statement that you want to cancel or report a fault.</li><li>You can use the <a href="downloads/cancellation-form.pdf">downloadable cancellation form</a>, but it is not compulsory.</li><li>Ask for the correct return address and instructions. The published correspondence address is not automatically a hardware returns depot. A request for instructions does not extend the legal return period.</li><li>Before returning a device, follow the appropriate account removal and data-erasure instructions. Do not send a device containing patient information without an agreed secure process.</li></ol><p>Return shipping for a change-of-mind cancellation is payable by the consumer only if this was properly disclosed before purchase. Reasonable return costs for faulty goods are handled under applicable consumer rights.</p>'),
        ('Refunds','<p>For an eligible cancellation, refunds are due within the applicable statutory period, normally within 14 days after the returned goods are received or evidence of return is provided, whichever comes first. We may withhold a refund until that point where the law permits.</p><p>The refund includes the original standard delivery cost. An additional amount paid for a premium delivery option need not be refunded. Refunds normally use the same payment method unless otherwise agreed without a fee.</p>'),
        ('Faults and digital services','<p>If goods are faulty, not as described or not fit for purpose, you have separate statutory remedies. For most goods, UK consumers have a short-term right to reject within 30 days; repair, replacement or further remedies may apply after that. Warranty terms cannot remove statutory rights.</p><p>Digital content and service rights are separate from goods cancellation. The digital supply terms must explain any relevant cancellation consequences; submitting an enquiry does not waive them.</p>'),
        ('Organisations and further help',f'<p>Business and organisational purchases may be governed by negotiated terms. Review the written agreement for delivery, acceptance and cancellation arrangements.</p><p>Contact {contact} for help. Read <a href="{returns}">GOV.UK guidance on returns and refunds</a> for an independent overview of consumer rights.</p>')
    ])
    document('acceptable-use.html','Acceptable use','Practical boundaries for using the website and discussing Bedbord and TESS.',[
        ('Respect people and information','<p>Do not submit another person’s medical records, health information or identifying screenshots through the marketing website. Share only the information necessary for the enquiry and only information you are entitled to share.</p><p>Do not use the website or products to harass, discriminate, exploit, impersonate or distribute unlawful content. Respect intellectual property and the privacy of residents, patients, families and staff.</p>'),
        ('Care and professional judgement','<p>Bedbord does not replace approved records, patient identification or clinical verification. TESS activities do not replace a clinician, carer, qualified interpreter or safeguarding process.</p><p>AI-generated content can be inaccurate or unsuitable. Do not use it for diagnosis, medication, treatment or emergency decisions. Supervise use where appropriate, and stop an activity if it causes discomfort or distress.</p>'),
        ('Accounts and devices','<p>Follow the product’s supplied instructions and your organisation’s access policies. Do not share staff credentials, bypass controls, install unapproved software or attempt to access another person’s information.</p><p>Before shared use, confirm appropriate accounts, content, permissions, cleaning and secure reset procedures. Only use approved power supplies and compatible accessories.</p>'),
        ('Reporting a concern',f'<p>If a concern affects immediate care, use the local clinical or emergency escalation route first. For product issues, contact {contact} with a factual description that excludes patient data. Product-specific contractual enforcement and suspension provisions must be set out in the relevant service agreement.</p>')
    ])
    legal_name=E(config['legalName']) if config['legalName'] else 'TruSelv'
    company_details=(f'<p>Legal entity: {legal_name}<br>Company number: {E(config["companyNumber"])}<br>Registered office: {E(config["registeredOffice"])}</p>' if config['legalName'] and config['companyNumber'] and config['registeredOffice'] else '<p>TruSelv is the brand used on this website. The legal seller and its registered details will be identified in the written offer before any purchase or organisational contract. This version of the site accepts enquiries; an enquiry does not form a sale contract.</p>')
    document('legal.html','Company & website information','Contact and contracting information for the TruSelv website.',[
        ('Website operator',company_details+f'<p>Website: {E(config["siteUrl"])}<br>Email: {contact}<br>Telephone: <a href="tel:+447920693839">{E(config["phone"])}</a><br>Correspondence: {E(config["address"])}</p><p>Please contact us before visiting or sending hardware. A correspondence address is not necessarily a registered office or returns depot.</p>'),
        ('Our product focus','<p>This website focuses on Bedbord and TESS. Legacy URLs may redirect to current product or information pages. Historic descriptions of other services are not part of the current offer.</p>'),
        ('Marks, imagery and evidence','<p>TruSelv, Bedbord and TESS are product and brand names used on this site. No registration status is implied by their presentation. Apple, App Store, Google Play and other third-party names belong to their respective owners; their mention does not imply endorsement.</p><p>Product films, interface examples and synthetic marketing photographs are illustrative. They are not evidence of a real customer deployment, NHS approval or measured clinical outcome. The <a href="trust.html">trust centre</a> describes the distinction between product discussion and assurance evidence.</p>'),
        ('Policies and contact','<p>Read the <a href="terms.html">website terms</a>, <a href="privacy.html">privacy notice</a>, <a href="sales-terms.html">sales terms</a> and <a href="returns.html">returns information</a> for the relevant subject.</p>'+f'<p>Report an error or ask a company question through {contact}.</p>')
    ])
    document('accessibility.html','Accessibility','Our approach to making this website understandable and usable, and how to request an alternative.',[
        ('Using this website','<p>The website uses clear headings, readable local fonts, visible focus states, labelled form fields and a skip-to-content link. Navigation, product gallery controls, FAQs and forms can be used with a keyboard. Content adapts to smaller screens, and browser zoom is not restricted.</p><p>Motion follows your device’s reduced-motion preference. The welcome film has pause and sound controls; product films use native playback controls. Sound is not started automatically. Product information is also explained in the page text.</p>'),
        ('Our target and limitations','<p>WCAG 2.2 Level AA informs the design. We do not claim independently audited conformance. Automated checks alone do not establish that a website works for every person or assistive technology.</p><p>Known limitations: supplied films do not yet have verified synchronised captions or audio description; text on an illustrative product screen may be small; downloadable PDFs are readable text documents but may not provide a fully tagged reading experience. Core product and privacy information is also available as HTML. Third-party email, app-store and payment services have their own accessibility behaviour.</p>'),
        ('Product accessibility','<p>Website accessibility is separate from Bedbord or TESS accessibility. Ask us to demonstrate the current product release with the input methods, vision, hearing, cognitive or communication needs relevant to your setting. We do not promise every activity is suitable for every user.</p>'),
        ('Request an alternative',f'<p>Email {contact} or call <a href="tel:+447920693839">{E(config["phone"])}</a>. Tell us the page or document, the difficulty you experienced and the format or adjustment that would help. You do not need to disclose a diagnosis.</p><p>We will discuss a practical alternative. For feedback, browser and assistive-technology details are helpful if you are comfortable providing them.</p>'),
        ('Review and reference',f'<p>This statement was prepared on {date}. The implementation is reviewed with keyboard, responsive-layout and automated checks. Further user testing, verified video captions and PDF accessibility review remain part of the improvement work.</p><p>Reference: <a href="https://www.w3.org/TR/WCAG22/">W3C Web Content Accessibility Guidelines 2.2</a>.</p>')
    ])
    body=hero('Trust centre','Clear information.<br>Considered decisions.','Trust is built through evidence, good questions and clear responsibilities. Here is how to approach the assessment of Bedbord and TESS.')
    body+='''<section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">A transparent starting point</p><h2>Ask for evidence.<br>Know what it covers.</h2></div><p>Requirements depend on the product, software release, intended use and deployment setting.</p></div><p class="note">This website does not publish verified ISO certificates, NHS DSPT status, a completed DTAC assessment, product conformity declarations or a clinical safety case. Their availability and applicability must be confirmed for the product you are assessing. Nothing here claims NHS approval or universal compliance.</p><div class="status-list">'''
    rows=[('Data protection','Clarify controller and processor roles, data flows, lawful basis, retention, hosting and any international transfers.','Deployment review'),('Clinical safety','Assess whether DCB0129 and DCB0160 apply. Request release-specific safety documentation, residual risks and local deployment responsibilities.','Evidence to confirm'),('Security','Discuss access controls, encryption, device updates, vulnerability handling, backups and incident response. Verify the implemented controls.','Evidence to confirm'),('Product conformity','Ask for the exact hardware model, intended-use statement, relevant conformity documents, cleaning guidance and electrical-safety information.','Evidence to confirm'),('Accessibility & usability','Test with representative users, realistic lighting and placement, and the interaction methods needed in your setting.','Local assessment'),('Integration & continuity','Confirm supported interfaces, update responsibility, downtime behaviour, data freshness and a safe fallback.','Deployment review')]
    body+=''.join(f'<div class="status-row"><h3>{t}</h3><p>{p}</p><span class="pill">{s}</span></div>' for t,p,s in rows)
    body+='</div><div class="actions"><a class="btn" href="downloads/procurement-checklist.pdf">Download the discussion checklist <span aria-hidden="true">↗</span></a><a class="text-link" href="contact.html?topic=Procurement%20evidence">Discuss an evidence request ↗</a></div></div></section><section class="section ivory"><div class="container three-grid"><article><h3>Product safety</h3><p>Intended use, local checks and what to do when information is unavailable or wrong.</p><a class="text-link" href="safety.html">Read the safety approach ↗</a></article><article><h3>Website privacy</h3><p>What the enquiry forms do with your information, and how to exercise your rights.</p><a class="text-link" href="privacy.html">Read the privacy notice ↗</a></article><article><h3>Accessible experiences</h3><p>Website features, known limitations and how to request another format.</p><a class="text-link" href="accessibility.html">Read accessibility information ↗</a></article></div></section>'+cta('Let’s ask the<br>right questions together.','Bring your clinical, digital and procurement colleagues into the conversation.')
    page('trust.html','Trust centre','A transparent starting point for Bedbord and TESS safety, data protection, security, accessibility and procurement questions.',body)
    document('safety.html','Product safety & responsible deployment','Practical safety considerations for introducing Bedbord or TESS into a care setting.',[
        ('Intended use and limits','<p>Bedbord is described on this website as a bedside information and communication display. TESS is described as a tablet-based engagement and communication experience. Neither is presented as a replacement for clinical judgement, approved records, staff observation or emergency systems.</p><p>A product name or marketing description does not settle medical-device classification. Request the manufacturer’s current intended-use statement and any applicable regulatory assessment for the exact release and hardware.</p>'),
        ('Bedbord information checks','<ul><li>Agree which information can be visible, to whom and in which physical location.</li><li>Identify who is responsible for updates and verification, including admission, transfers and discharge.</li><li>Assess the risk of stale, missing or misattributed information and how the system makes it apparent.</li><li>Verify identity, allergies and clinical decisions through your approved records and procedures.</li><li>Define a usable fallback for device, network or power failure and train staff in it.</li></ul>'),
        ('TESS supported use','<p>Choose activities around the person’s preferences and current support needs. AI conversation may be inaccurate; sign-based tools are not a substitute for a qualified interpreter. Do not use entertainment or AI outputs for clinical advice.</p><p>Agree supervision, safeguarding, content permissions, volume and shared-account arrangements. Give the person a way to stop, change activity or decline. Confirm handling, charging, connectivity and cleaning instructions before introducing a device.</p>'),
        ('Local deployment assessment','<p>Include clinical, digital, information-governance, accessibility, infection-prevention and procurement stakeholders as appropriate. Review device placement, mounting, cables, electrical requirements, visibility and cleaning. Do not infer approved disinfectants or electrical suitability from the look of a device.</p><p>Where applicable, DCB0129 concerns clinical risk management by health IT manufacturers and DCB0160 concerns deployment and use by health and care organisations. Applicability and evidence must be assessed for the intended use; a marketing page cannot establish conformance.</p>'),
        ('Reporting and escalation',f'<p>If an issue could affect immediate care, follow the local clinical escalation route first and use approved alternatives. Report the product issue to your organisation’s responsible lead and {contact}. Include the product, version, device identifier and a description without personal health data.</p><p>Product-specific support commitments, incident routes and responsibilities must be recorded in the deployment agreement. This website is not a continuously monitored clinical incident service.</p>'),
        ('Evidence and references','<p>Use the <a href="trust.html">trust centre</a> and <a href="downloads/procurement-checklist.pdf">procurement discussion checklist</a> to structure an evidence request.</p><p>Reference: <a href="https://service-manual.nhs.uk/standards-and-technology/service-standard-points/16-make-your-service-clinically-safe">NHS service standard: make your service clinically safe</a>. The <a href="https://www.england.nhs.uk/long-read/national-review-of-clinical-risk-management-standardsdcb0129-and-dcb0160-supporting-information/">NHS review of DCB0129 and DCB0160</a> provides current context on the standards review.</p>')
    ])
