import {adminResources} from '../website-content/content.mjs';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(error,status=400)=>json({error},status), id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const roles=['truselv_admin','facility_admin','facility_head','activities_lead','viewer','ward_analytics'];
const ticketCategories=['device','login-access','licence','app-feature','connectivity','resident-records','billing','training','other'];
const ticketStatuses=['new','open','waiting','resolved','closed'],ticketPriorities=['low','normal','high','urgent'];
const manage=r=>['truselv_admin','facility_admin'].includes(r),facilityStructure=r=>['facility_admin','facility_head'].includes(r),residents=r=>['truselv_admin','facility_admin','facility_head','activities_lead'].includes(r);
const outcomeTags=['enjoyment','social_connection','communication','cognitive_stimulation','physical_movement','relaxation','independence_choice'];
const wellbeingChanges=['improved','unchanged','declined','not_observed'];
const text=(v,max)=>typeof v==='string'&&v.trim()&&v.trim().length<=max?v.trim():null;
const b64=b=>btoa(String.fromCharCode(...b));
async function digest(v){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))));}
async function authDigest(env,value){const key=await crypto.subtle.importKey('raw',Uint8Array.from(atob(env.FIELD_ENCRYPTION_KEY),x=>x.charCodeAt(0)),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value))));}
const cookie=(request,name)=>(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1)||'';
const sessionCookie=token=>`tess_portal_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200`;
const expiredSessionCookie='tess_portal_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0';
function sameOrigin(request){const origin=request.headers.get('Origin');if(origin&&origin!==new URL(request.url).origin)throw Object.assign(Error('Request origin denied.'),{status:403});}
async function secureEqual(left,right){const a=Uint8Array.from(atob(left),x=>x.charCodeAt(0)),b=Uint8Array.from(atob(right),x=>x.charCodeAt(0));if(a.length!==b.length)return false;let difference=0;for(let i=0;i<a.length;i++)difference|=a[i]^b[i];return difference===0;}
async function input(request){if(Number(request.headers.get('content-length')||0)>65536)throw Object.assign(Error('Request is too large.'),{status:413});try{return await request.json();}catch{throw Object.assign(Error('Invalid JSON body.'),{status:400});}}
function permitted(user,test){if(!test(user.role))throw Object.assign(Error('You do not have permission for this action.'),{status:403});}
function scope(user,wanted){if(user.role==='truselv_admin')return wanted;if(!user.facility_id||(wanted&&wanted!==user.facility_id))throw Object.assign(Error('Facility access denied.'),{status:403});return user.facility_id;}
async function userFor(request,env){const portalHost=new URL(request.url).hostname===env.PORTAL_HOST;let user;if(portalHost){const token=cookie(request,'tess_portal_session');if(!token)throw Object.assign(Error('Sign in is required.'),{status:401});user=await env.DB.prepare(`SELECT u.id,u.facility_id,u.ward_id,u.email,u.role,u.active,f.name facility_name,f.status facility_status,w.name ward_name,s.id session_id FROM portal_sessions s JOIN facility_users u ON u.id=s.user_id LEFT JOIN facilities f ON f.id=u.facility_id LEFT JOIN wards w ON w.id=u.ward_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1 LIMIT 1`).bind(await digest(token),now()).first();if(user)await env.DB.prepare('UPDATE portal_sessions SET last_seen_at=? WHERE id=?').bind(now(),user.session_id).run();}else{const email=(request.headers.get(env.ACCESS_HEADER||'Cf-Access-Authenticated-User-Email')||env.DEV_IDENTITY_EMAIL||'').trim().toLowerCase();if(!email)throw Object.assign(Error('Sign in is required.'),{status:401});user=await env.DB.prepare(`SELECT u.id,u.facility_id,u.ward_id,u.email,u.role,u.active,f.name facility_name,f.status facility_status,w.name ward_name FROM facility_users u LEFT JOIN facilities f ON f.id=u.facility_id LEFT JOIN wards w ON w.id=u.ward_id WHERE u.email=? AND u.active=1 LIMIT 1`).bind(email).first();}if(!user||(user.facility_id&&user.facility_status!=='active'))throw Object.assign(Error('Your account does not have active portal access.'),{status:portalHost?401:403});return user;}
async function ward(env,facilityId,wardId,required=false){if(!wardId){if(required)throw Object.assign(Error('Choose a ward.'),{status:400});return null;}const row=await env.DB.prepare('SELECT id,name FROM wards WHERE id=? AND facility_id=? AND active=1').bind(wardId,facilityId).first();if(!row)throw Object.assign(Error('Ward access denied.'),{status:403});return row;}
async function wardScope(env,user,facilityId,wanted,required=false){const selected=user.role==='ward_analytics'?user.ward_id:(wanted||null);if(user.role==='ward_analytics'&&wanted&&wanted!==user.ward_id)throw Object.assign(Error('Ward access denied.'),{status:403});return ward(env,facilityId,selected,required);}
async function audit(env,user,action,type,target,details={}){await env.DB.prepare('INSERT INTO audit_log (id,facility_id,actor_email,action,target_type,target_id,details_json) VALUES (?,?,?,?,?,?,?)').bind(id(),user.facility_id||null,user.email,action,type,target,JSON.stringify(details)).run();}
async function cryptoKey(env){if(!env.FIELD_ENCRYPTION_KEY)throw Object.assign(Error('Portal encryption is not configured.'),{status:503});const raw=Uint8Array.from(atob(env.FIELD_ENCRYPTION_KEY),x=>x.charCodeAt(0));if(raw.length!==32)throw Object.assign(Error('Portal encryption configuration is invalid.'),{status:503});return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}
async function encrypt(env,value){const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptoKey(env),new TextEncoder().encode(value));return `${b64(iv)}.${b64(new Uint8Array(data))}`;}
async function decrypt(env,value){const [iv,data]=value.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(atob(iv),x=>x.charCodeAt(0))},await cryptoKey(env),Uint8Array.from(atob(data),x=>x.charCodeAt(0))));}
async function device(request,env){const m=/^Bearer\s+(.+)$/i.exec(request.headers.get('Authorization')||'');if(!m)throw Object.assign(Error('A device key is required.'),{status:401});const row=await env.DB.prepare('SELECT d.*,l.status licence_status,f.name facility_name,f.plan facility_plan,f.terminology_person,f.terminology_unit,w.name ward_name FROM devices d LEFT JOIN licences l ON l.id=d.licence_id JOIN facilities f ON f.id=d.facility_id JOIN wards w ON w.id=d.ward_id WHERE d.activation_token_hash=? LIMIT 1').bind(await digest(m[1])).first();if(!row)throw Object.assign(Error('Device access denied.'),{status:401});return row;}
const configurableFeatures=['chatroom','conversation-starters','communication','caregiver','faith','health','games','radio','live-tv','youtube','music','books','podcasts','moments','places','british-sign-language','browser'];
function defaultOrganisationConfig(d){return {schemaVersion:1,version:0,plan:d.facility_plan||'organisation',branding:{displayName:d.facility_name},terminology:{person:d.terminology_person||'resident',unit:d.terminology_unit||'ward'},features:Object.fromEntries(configurableFeatures.map(feature=>[feature,true])),homeTiles:configurableFeatures,policies:{idleMinutes:5,browserMode:'safe'}};}
async function organisationConfig(env,d){const row=await env.DB.prepare("SELECT version,schema_version,config_json FROM organisation_config_versions WHERE facility_id=? AND status='published' ORDER BY version DESC LIMIT 1").bind(d.facility_id).first();let config=defaultOrganisationConfig(d);if(row){try{const parsed=JSON.parse(row.config_json);if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))config={...config,...parsed,schemaVersion:Number(row.schema_version)||1,version:Number(row.version)||0,plan:d.facility_plan||parsed.plan||'organisation'};}catch{throw Object.assign(Error('The organisation configuration is invalid.'),{status:503});}}const entitlements=(await env.DB.prepare('SELECT feature_id,enabled FROM organisation_entitlements WHERE facility_id=?').bind(d.facility_id).all()).results;if(entitlements.length){const allowed=new Map(entitlements.map(x=>[x.feature_id,Boolean(x.enabled)]));config.features=Object.fromEntries(configurableFeatures.map(feature=>[feature,Boolean(config.features?.[feature])&&allowed.get(feature)===true]));}return config;}
async function deviceResident(env,d){if(d.device_mode==='dedicated')return d.assigned_resident_id||null;const active=await env.DB.prepare("SELECT s.id,s.mode,s.anonymous,p.resident_id FROM activity_sessions s LEFT JOIN activity_session_residents p ON p.session_id=s.id WHERE s.device_id=? AND s.status='active' ORDER BY s.started_at DESC LIMIT 2").bind(d.id).all(),rows=active.results;if(rows.length!==1||rows[0].anonymous||rows[0].mode!=='individual')return null;return rows[0].resident_id||null;}
function validatedOrganisationConfig(value,facility){if(!value||typeof value!=='object'||Array.isArray(value))throw Object.assign(Error('Enter a valid organisation configuration.'),{status:400});const features=value.features&&typeof value.features==='object'&&!Array.isArray(value.features)?Object.fromEntries(configurableFeatures.map(feature=>[feature,value.features[feature]===true])):Object.fromEntries(configurableFeatures.map(feature=>[feature,true])),homeTiles=Array.isArray(value.homeTiles)?[...new Set(value.homeTiles.filter(feature=>configurableFeatures.includes(feature)&&features[feature]))]:configurableFeatures.filter(feature=>features[feature]),branding=value.branding&&typeof value.branding==='object'?value.branding:{},terminology=value.terminology&&typeof value.terminology==='object'?value.terminology:{},policies=value.policies&&typeof value.policies==='object'?value.policies:{},displayName=text(branding.displayName,150)||facility.name,logoUrl=text(branding.logoUrl,1000),primaryColour=text(branding.primaryColour,7),person=text(terminology.person,40)||facility.terminology_person||'resident',unit=text(terminology.unit,40)||facility.terminology_unit||'ward',idleMinutes=Math.min(60,Math.max(1,Number(policies.idleMinutes)||5)),browserMode=['safe','allowlist','disabled'].includes(policies.browserMode)?policies.browserMode:'safe';if(logoUrl&&!/^https:\/\//i.test(logoUrl))throw Object.assign(Error('The organisation logo must use an HTTPS URL.'),{status:400});if(primaryColour&&!/^#[0-9a-f]{6}$/i.test(primaryColour))throw Object.assign(Error('Enter a six-digit hexadecimal brand colour.'),{status:400});return {schemaVersion:1,plan:facility.plan||'organisation',branding:{displayName,...(logoUrl?{logoUrl}:{}),...(primaryColour?{primaryColour:primaryColour.toUpperCase()}: {})},terminology:{person,unit},features,homeTiles,policies:{idleMinutes,browserMode}};}
async function cloudflare(env,path,options={}){if(!env.CF_ACCESS_API_TOKEN||!env.CF_ACCOUNT_ID)throw Object.assign(Error('Portal invitations are not configured yet.'),{status:503});const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}${path}`,{...options,headers:{Authorization:`Bearer ${env.CF_ACCESS_API_TOKEN}`,'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json();if(!response.ok||!data.success)throw Object.assign(Error(data.errors?.[0]?.message||'Cloudflare Access could not update the invitation.'),{status:502});return data.result;}
async function allowPortalEmail(env,email){const apps=await cloudflare(env,'/access/apps?per_page=100');const app=apps.find(x=>x.domain===env.PORTAL_HOST);if(!app)throw Object.assign(Error('The portal Access application could not be found.'),{status:503});const policies=await cloudflare(env,`/access/apps/${app.id}/policies?per_page=100`),normalised=email.toLowerCase(),existing=policies.find(policy=>policy.decision==='allow'&&policy.include?.some(rule=>rule.email?.email?.toLowerCase()===normalised));if(existing)return existing.id;const precedence=Math.max(0,...policies.map(x=>Number(x.precedence)||0))+1;const created=await cloudflare(env,`/access/apps/${app.id}/policies`,{method:'POST',body:JSON.stringify({name:`TESS portal invitation: ${email}`,decision:'allow',include:[{email:{email}}],precedence})});return created.id;}
async function sendMail(env,{to,subject,text:body,idempotencyKey}){if(!env.RESEND_API_KEY||!env.PORTAL_INVITE_FROM)return false;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':idempotencyKey},body:JSON.stringify({from:env.PORTAL_INVITE_FROM,to:[to],subject,text:body}),signal:AbortSignal.timeout(10000)});if(!response.ok)return false;return Boolean((await response.json()).id);}
async function resend(env,path,options={}){if(!env.RESEND_API_KEY)throw Object.assign(Error('Marketing updates are not configured yet.'),{status:503});const response=await fetch(`https://api.resend.com${path}`,{...options,headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json',...(options.headers||{})},signal:AbortSignal.timeout(15000)});const data=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(Error(data.message||'The email service could not complete this request.'),{status:502});return data;}
async function marketingSegment(env){if(env.RESEND_MARKETING_SEGMENT_ID)return env.RESEND_MARKETING_SEGMENT_ID;const listed=await resend(env,'/segments?limit=100'),existing=(listed.data||[]).find(x=>x.name==='TruSelv Updates');if(existing)return existing.id;const created=await resend(env,'/segments',{method:'POST',body:JSON.stringify({name:'TruSelv Updates'})});if(!created.id)throw Object.assign(Error('The marketing contact list could not be prepared.'),{status:502});return created.id;}
const htmlEscape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function marketingHtml(message,linkUrl,linkLabel){const paragraphs=message.split(/\n{2,}/).map(p=>`<p style="margin:0 0 16px">${htmlEscape(p).replaceAll('\n','<br>')}</p>`).join(''),button=linkUrl?`<p style="margin:24px 0"><a href="${htmlEscape(linkUrl)}" style="background:#08786f;color:#fff;padding:12px 18px;border-radius:6px;text-decoration:none;font-weight:700">${htmlEscape(linkLabel||'Learn more')}</a></p>`:'';return `<!doctype html><html><body style="margin:0;background:#f4f7f5;color:#14283b;font:16px/1.6 Arial,sans-serif"><div style="max-width:620px;margin:auto;padding:36px 22px"><div style="background:#fff;border:1px solid #d9dedb;border-radius:14px;padding:32px"><strong style="font-size:22px">TruSelv</strong><p>Hi {{{FIRST_NAME|there}}},</p>${paragraphs}${button}<p style="margin-top:28px;color:#49606f;font-size:13px">You received this because you asked for occasional TruSelv updates. <a href="{{{RESEND_UNSUBSCRIBE_URL}}}">Unsubscribe</a>.</p></div></div></body></html>`;}
async function sendInvitation(env,{email,facilityName,role,userId,attemptId='initial'}){const portalUrl=`https://${env.PORTAL_HOST}`;return sendMail(env,{to:email,subject:`You have been invited to the ${facilityName} TESS Facility Portal`,idempotencyKey:`tess-portal-invite-v3/${userId}/${attemptId}`,text:`Hello,\n\nYou have been granted ${role.replaceAll('_',' ')} access to the TESS Facility Portal for ${facilityName}.\n\nOpen the secure portal:\n${portalUrl}\n\nEnter this approved email address (${email}) and TruSelv will send your six-digit sign-in code.\n\nIf you were not expecting this invitation, please contact support@truselv.co.uk.\n\nTruSelv`});}
const ticketReference=()=>`TESS-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,4).toUpperCase()}`;
async function requestLogin(request,env){sameOrigin(request);const email=text((await input(request)).email,254)?.toLowerCase(),challengeId=id(),ipHash=await digest(request.headers.get('CF-Connecting-IP')||'unknown'),generic=()=>json({challengeId,message:'If this email has active portal access, a sign-in code has been sent.'});if(!email||!/^\S+@\S+\.\S+$/.test(email))return generic();const user=await env.DB.prepare(`SELECT u.id,u.email,f.name facility_name FROM facility_users u JOIN facilities f ON f.id=u.facility_id WHERE u.email=? AND u.active=1 AND f.status='active' AND u.role!='truselv_admin' LIMIT 1`).bind(email).first();if(!user)return generic();const [byUser,byIp]=await Promise.all([env.DB.prepare("SELECT COUNT(*) count FROM portal_login_challenges WHERE user_id=? AND created_at>=datetime('now','-15 minutes')").bind(user.id).first(),env.DB.prepare("SELECT COUNT(*) count FROM portal_login_challenges WHERE request_ip_hash=? AND created_at>=datetime('now','-15 minutes')").bind(ipHash).first()]);if(Number(byUser.count)>=5||Number(byIp.count)>=20)return generic();const code=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0'),expiresAt=new Date(Date.now()+600000).toISOString(),codeHash=await authDigest(env,`${challengeId}.${code}`);await env.DB.prepare('INSERT INTO portal_login_challenges (id,user_id,code_hash,request_ip_hash,expires_at) VALUES (?,?,?,?,?)').bind(challengeId,user.id,codeHash,ipHash,expiresAt).run();const sent=await sendMail(env,{to:user.email,subject:'Your TruSelv sign-in code',idempotencyKey:`tess-login-code/${challengeId}`,text:`Your TruSelv sign-in code is:\n\n${code}\n\nIt expires in 10 minutes and can be used once.\n\nFacility: ${user.facility_name}\nPortal: https://${env.PORTAL_HOST}\n\nIf you did not request this code, you can ignore this email.\n\nTruSelv`});if(!sent)throw Object.assign(Error('We could not send the sign-in email. Please try again shortly.'),{status:502});return generic();}
async function verifyLogin(request,env){sameOrigin(request);const v=await input(request),challengeId=text(v.challengeId,64),code=text(v.code,6);if(!challengeId||!/^\d{6}$/.test(code||''))return fail('Enter the six-digit code from your email.',400);const challenge=await env.DB.prepare(`SELECT c.id,c.user_id,c.code_hash,c.attempts,c.expires_at,c.used_at,u.active,f.status facility_status FROM portal_login_challenges c JOIN facility_users u ON u.id=c.user_id JOIN facilities f ON f.id=u.facility_id WHERE c.id=? LIMIT 1`).bind(challengeId).first();if(!challenge||challenge.used_at||challenge.attempts>=5||challenge.expires_at<=now()||!challenge.active||challenge.facility_status!=='active')return fail('This code is invalid or has expired. Request a new code.',401);await env.DB.prepare('UPDATE portal_login_challenges SET attempts=attempts+1 WHERE id=?').bind(challengeId).run();if(!await secureEqual(challenge.code_hash,await authDigest(env,`${challengeId}.${code}`)))return fail('This code is incorrect. Please try again.',401);const token=b64(crypto.getRandomValues(new Uint8Array(32))),sessionId=id(),expiresAt=new Date(Date.now()+43200000).toISOString();await env.DB.batch([env.DB.prepare('UPDATE portal_login_challenges SET used_at=? WHERE id=?').bind(now(),challengeId),env.DB.prepare('INSERT INTO portal_sessions (id,user_id,token_hash,expires_at) VALUES (?,?,?,?)').bind(sessionId,challenge.user_id,await digest(token),expiresAt),env.DB.prepare('DELETE FROM portal_sessions WHERE expires_at<=?').bind(now())]);return new Response(JSON.stringify({ok:true}),{headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Set-Cookie':sessionCookie(token),'X-Content-Type-Options':'nosniff'}});}
async function dashboard(env,facilityId,wardId,seeResidents){
 const where=wardId?'facility_id=? AND ward_id=?':'facility_id=?',args=wardId?[facilityId,wardId]:[facilityId];
 const sessionWhere=wardId?'s.facility_id=? AND s.ward_id=?':'s.facility_id=?';
 const [dev,lic,events,features,people,sessions,residentActivity]=await Promise.all([
  env.DB.prepare(`SELECT COUNT(*) count FROM devices WHERE ${where} AND status='active'`).bind(...args).first(),
  env.DB.prepare("SELECT COUNT(*) count FROM licences WHERE facility_id=? AND status='active'").bind(facilityId).first(),
  env.DB.prepare(`SELECT COUNT(*) count FROM usage_events WHERE ${where} AND occurred_at>=datetime('now','-30 days')`).bind(...args).first(),
  env.DB.prepare(`SELECT feature,COUNT(*) count FROM usage_events WHERE ${where} AND occurred_at>=datetime('now','-30 days') GROUP BY feature ORDER BY count DESC LIMIT 5`).bind(...args).all(),
  seeResidents?env.DB.prepare(`SELECT COUNT(*) count FROM residents WHERE ${where} AND active=1`).bind(...args).first():Promise.resolve(null),
  env.DB.prepare(`SELECT COUNT(*) count,SUM(CASE WHEN mode='individual' THEN 1 ELSE 0 END) individual_count,SUM(CASE WHEN mode='group' THEN 1 ELSE 0 END) group_count,SUM(CASE WHEN anonymous=1 THEN 1 ELSE 0 END) anonymous_count FROM activity_sessions s WHERE ${sessionWhere} AND started_at>=datetime('now','-30 days')`).bind(...args).first(),
  seeResidents?env.DB.prepare(`SELECT r.id,r.first_name_cipher,r.last_name_cipher,COUNT(DISTINCT s.id) session_count FROM activity_sessions s JOIN activity_session_residents sr ON sr.session_id=s.id JOIN residents r ON r.id=sr.resident_id WHERE ${sessionWhere} AND s.started_at>=datetime('now','-30 days') GROUP BY r.id ORDER BY session_count DESC LIMIT 10`).bind(...args).all():Promise.resolve({results:[]})
 ]);
 const residentUsage=await Promise.all(residentActivity.results.map(async r=>({id:r.id,name:`${await decrypt(env,r.first_name_cipher)} ${await decrypt(env,r.last_name_cipher)}`.trim(),sessions:r.session_count})));
 return {activeDevices:dev.count,activeLicences:lic.count,interactions30d:events.count,featureUsage:features.results,residents:people?.count??null,sessions30d:Number(sessions.count)||0,individualSessions:Number(sessions.individual_count)||0,groupSessions:Number(sessions.group_count)||0,anonymousSessions:Number(sessions.anonymous_count)||0,residentUsage};
}
async function analytics(env,facilityId,wardId,user,url){
 const today=new Date(),defaultFrom=new Date(today.getTime()-29*86400000).toISOString().slice(0,10),from=/^\d{4}-\d{2}-\d{2}$/.test(url.searchParams.get('from')||'')?url.searchParams.get('from'):defaultFrom,to=/^\d{4}-\d{2}-\d{2}$/.test(url.searchParams.get('to')||'')?url.searchParams.get('to'):today.toISOString().slice(0,10),mode=['individual','group','anonymous'].includes(url.searchParams.get('mode'))?url.searchParams.get('mode'):null,residentId=text(url.searchParams.get('residentId'),64),named=residents(user.role);
 if(from>to)return fail('The start date must be before the end date.');
 if((Date.parse(to)-Date.parse(from))/86400000>731)return fail('Choose a date range of two years or less.');
 const conditions=['s.facility_id=?','date(s.started_at)>=?','date(s.started_at)<=?'],args=[facilityId,from,to];
 if(wardId){conditions.push('s.ward_id=?');args.push(wardId);}
 if(mode==='anonymous')conditions.push('s.anonymous=1');
 else if(mode){conditions.push('s.anonymous=0','s.mode=?');args.push(mode);}
 if(residentId){if(!named)return fail('Resident-level analytics are not available for this role.',403);const resident=await env.DB.prepare('SELECT id FROM residents WHERE id=? AND facility_id=? AND active=1').bind(residentId,facilityId).first();if(!resident)return fail('Resident not found.',404);conditions.push('EXISTS (SELECT 1 FROM activity_session_residents fx WHERE fx.session_id=s.id AND fx.resident_id=?)');args.push(residentId);}
 const where=conditions.join(' AND '),bind=statement=>statement.bind(...args);
 const [summary,daily,modes,features,engagement,wellbeing,outcomes,people,sessionRows,wards,availableResidents]=await Promise.all([
  bind(env.DB.prepare(`SELECT COUNT(DISTINCT s.id) sessions,COUNT(DISTINCT sr.resident_id) residents,COUNT(sr.resident_id) participations,ROUND(AVG(o.engagement_level),1) avg_engagement,SUM(CASE WHEN o.wellbeing_change='improved' THEN 1 ELSE 0 END) improved FROM activity_sessions s LEFT JOIN activity_session_residents sr ON sr.session_id=s.id LEFT JOIN session_outcomes o ON o.session_id=s.id AND o.resident_id IS sr.resident_id WHERE ${where}`)).first(),
  bind(env.DB.prepare(`SELECT date(s.started_at) day,COUNT(DISTINCT s.id) count FROM activity_sessions s WHERE ${where} GROUP BY day ORDER BY day`)).all(),
  bind(env.DB.prepare(`SELECT CASE WHEN s.anonymous=1 THEN 'anonymous' ELSE s.mode END label,COUNT(*) count FROM activity_sessions s WHERE ${where} GROUP BY label ORDER BY count DESC`)).all(),
  bind(env.DB.prepare(`SELECT u.feature label,COUNT(*) count FROM activity_sessions s JOIN usage_events u ON u.session_id=s.id WHERE ${where} GROUP BY u.feature ORDER BY count DESC LIMIT 12`)).all(),
  bind(env.DB.prepare(`SELECT o.engagement_level label,COUNT(*) count FROM activity_sessions s JOIN session_outcomes o ON o.session_id=s.id WHERE ${where} GROUP BY o.engagement_level ORDER BY o.engagement_level`)).all(),
  bind(env.DB.prepare(`SELECT o.wellbeing_change label,COUNT(*) count FROM activity_sessions s JOIN session_outcomes o ON o.session_id=s.id WHERE ${where} GROUP BY o.wellbeing_change ORDER BY count DESC`)).all(),
  bind(env.DB.prepare(`SELECT j.value label,COUNT(*) count FROM activity_sessions s JOIN session_outcomes o ON o.session_id=s.id JOIN json_each(o.outcome_tags_json) j WHERE ${where} GROUP BY j.value ORDER BY count DESC`)).all(),
  named?bind(env.DB.prepare(`SELECT r.id,r.first_name_cipher,r.last_name_cipher,COUNT(DISTINCT s.id) sessions,ROUND(AVG(o.engagement_level),1) avg_engagement,SUM(CASE WHEN o.wellbeing_change='improved' THEN 1 ELSE 0 END) improved FROM activity_sessions s JOIN activity_session_residents sr ON sr.session_id=s.id JOIN residents r ON r.id=sr.resident_id LEFT JOIN session_outcomes o ON o.session_id=s.id AND o.resident_id=r.id WHERE ${where} GROUP BY r.id ORDER BY sessions DESC,r.created_at LIMIT 250`)).all():Promise.resolve({results:[]}),
  named?bind(env.DB.prepare(`SELECT s.id,s.started_at,s.ended_at,s.mode,s.anonymous,w.name ward_name,sr.resident_id,r.first_name_cipher,r.last_name_cipher,o.engagement_level,o.wellbeing_change,o.outcome_tags_json,GROUP_CONCAT(DISTINCT u.feature) features FROM activity_sessions s JOIN wards w ON w.id=s.ward_id LEFT JOIN activity_session_residents sr ON sr.session_id=s.id LEFT JOIN residents r ON r.id=sr.resident_id LEFT JOIN session_outcomes o ON o.session_id=s.id AND o.resident_id IS sr.resident_id LEFT JOIN usage_events u ON u.session_id=s.id WHERE ${where} GROUP BY s.id,sr.resident_id ORDER BY s.started_at DESC LIMIT 1000`)).all():Promise.resolve({results:[]}),
  env.DB.prepare('SELECT id,name FROM wards WHERE facility_id=? AND active=1 ORDER BY name').bind(facilityId).all(),
  named?env.DB.prepare(`SELECT id,first_name_cipher,last_name_cipher FROM residents WHERE facility_id=? AND active=1${wardId?' AND ward_id=?':''} ORDER BY created_at`).bind(facilityId,...(wardId?[wardId]:[])).all():Promise.resolve({results:[]})
 ]);
 const decryptName=async r=>`${await decrypt(env,r.first_name_cipher)} ${await decrypt(env,r.last_name_cipher)}`.trim();
 const reached=new Map(people.results.map(r=>[r.id,r]));
 const rows=await Promise.all(sessionRows.results.map(async r=>({sessionId:r.id,date:r.started_at,endedAt:r.ended_at,mode:r.anonymous?'anonymous':r.mode,ward:r.ward_name,residentId:r.resident_id,resident:r.resident_id?await decryptName(r):'Anonymous',features:(r.features||'').split(',').filter(Boolean),engagement:r.engagement_level,wellbeingChange:r.wellbeing_change,outcomeTags:JSON.parse(r.outcome_tags_json||'[]')})));
 const residentOptions=await Promise.all(availableResidents.results.map(async r=>({id:r.id,name:await decryptName(r)})));
 const residentResults=residentOptions.map(r=>{const result=reached.get(r.id);return {...r,sessions:Number(result?.sessions)||0,averageEngagement:Number(result?.avg_engagement)||0,improved:Number(result?.improved)||0};});
 return json({filters:{from,to,mode,residentId,wards:wards.results,residents:residentOptions},summary:{sessions:Number(summary.sessions)||0,residents:Number(summary.residents)||0,notReached:Math.max(0,residentOptions.length-(Number(summary.residents)||0)),participations:Number(summary.participations)||0,averageEngagement:Number(summary.avg_engagement)||0,improved:Number(summary.improved)||0},daily:daily.results,modes:modes.results,features:features.results,engagement:engagement.results,wellbeing:wellbeing.results,outcomes:outcomes.results,residents:residentResults,rows,cqc:[{area:'Effective',statement:'Monitoring and improving outcomes',evidence:'Participation, engagement and observed outcome trends'},{area:'Effective',statement:'Supporting people to live healthier lives',evidence:'Physical, social and wellbeing activity participation'},{area:'Caring',statement:'Treating people as individuals',evidence:'Resident-specific activity history and preferences'},{area:'Caring',statement:'Independence, choice and control',evidence:'Access to activities and recorded choice outcomes'},{area:'Responsive',statement:'Person-centred care',evidence:'Individual participation and outcome evidence'},{area:'Well-led',statement:'Governance, management and sustainability',evidence:'Coverage, gaps and service-level trends'}]});
}
async function api(request,env,url){
 if(!env.DB)return fail('Database binding is not configured.',503);
 if(url.hostname===env.PORTAL_HOST&&url.pathname==='/api/auth/request'&&request.method==='POST')return requestLogin(request,env);
 if(url.hostname===env.PORTAL_HOST&&url.pathname==='/api/auth/verify'&&request.method==='POST')return verifyLogin(request,env);
 if(url.hostname===env.PORTAL_HOST&&url.pathname==='/api/auth/logout'&&request.method==='GET'){const token=cookie(request,'tess_portal_session');if(token)await env.DB.prepare('DELETE FROM portal_sessions WHERE token_hash=?').bind(await digest(token)).run();return new Response(null,{status:303,headers:{Location:'/', 'Set-Cookie':expiredSessionCookie,'Cache-Control':'no-store'}});}
 if(url.pathname==='/api/device/bootstrap'&&request.method==='GET'){const d=await device(request,env),config=await organisationConfig(env,d),commands=(await env.DB.prepare("SELECT id,command,payload_json,created_at FROM device_commands WHERE device_id=? AND status='pending' ORDER BY created_at LIMIT 20").bind(d.id).all()).results.map(command=>({id:command.id,command:command.command,payload:JSON.parse(command.payload_json||'{}'),createdAt:command.created_at}));await env.DB.prepare('UPDATE devices SET last_seen_at=?,configuration_version=? WHERE id=?').bind(now(),Number(config.version)||0,d.id).run();return json({deviceId:d.id,facilityId:d.facility_id,facilityName:d.facility_name,wardId:d.ward_id,wardName:d.ward_name,status:d.status,licenceStatus:d.licence_status||'missing',enabled:d.status==='active'&&d.licence_status==='active',deviceMode:d.device_mode||'shared',assignedResidentId:d.assigned_resident_id||null,lifecycleState:d.lifecycle_state||'ready',organisationConfig:config,commands});}
 if(url.pathname==='/api/device/activate'&&request.method==='POST'){const d=await device(request,env);if(['retired','suspended'].includes(d.status)||d.licence_status!=='active')return fail('This device cannot be activated.',403);await env.DB.prepare("UPDATE devices SET status='active',last_seen_at=? WHERE id=?").bind(now(),d.id).run();return json({deviceId:d.id,status:'active'});}
 if(url.pathname==='/api/device/context'&&request.method==='GET'){const d=await device(request,env);if(d.status!=='active'||d.licence_status!=='active')return fail('This device is not active.',403);const dedicated=d.device_mode==='dedicated';if(dedicated&&!d.assigned_resident_id)return fail('This dedicated tablet is ready for a resident assignment.',409);const requestedWardId=dedicated?d.ward_id:(text(url.searchParams.get('wardId'),64)||d.ward_id),selectedWard=await env.DB.prepare('SELECT id,name FROM wards WHERE id=? AND facility_id=? AND active=1').bind(requestedWardId,d.facility_id).first();if(!selectedWard)return fail('Choose an active ward in this facility.',400);const wards=dedicated?[selectedWard]:(await env.DB.prepare('SELECT id,name FROM wards WHERE facility_id=? AND active=1 ORDER BY lower(name)').bind(d.facility_id).all()).results,query=dedicated?'SELECT id,ward_id,first_name_cipher,last_name_cipher FROM residents WHERE facility_id=? AND id=? AND active=1':'SELECT id,ward_id,first_name_cipher,last_name_cipher FROM residents WHERE facility_id=? AND ward_id=? AND active=1 ORDER BY created_at',rows=(await env.DB.prepare(query).bind(d.facility_id,dedicated?d.assigned_resident_id:selectedWard.id).all()).results;if(dedicated&&rows.length!==1)return fail('The assigned resident is no longer available.',409);const residentRows=await Promise.all(rows.map(async r=>({id:r.id,wardId:r.ward_id,name:`${await decrypt(env,r.first_name_cipher)} ${await decrypt(env,r.last_name_cipher)}`.trim()}))),active=await env.DB.prepare("SELECT id,mode,anonymous,started_at FROM activity_sessions WHERE device_id=? AND status='active' ORDER BY started_at DESC LIMIT 1").bind(d.id).first();let participantIds=[];if(active)participantIds=(await env.DB.prepare('SELECT resident_id FROM activity_session_residents WHERE session_id=?').bind(active.id).all()).results.map(x=>x.resident_id);return json({deviceMode:d.device_mode||'shared',assignedResidentId:d.assigned_resident_id||null,wards,residents:residentRows,activeSession:active?{id:active.id,mode:active.mode,anonymous:Boolean(active.anonymous),startedAt:active.started_at,residentIds:participantIds}:null});}
 if(url.pathname==='/api/device/sessions/start'&&request.method==='POST'){const d=await device(request,env);if(d.status!=='active'||d.licence_status!=='active')return fail('This device is not active.',403);const v=await input(request),dedicated=d.device_mode==='dedicated',mode=dedicated?'individual':text(v.mode,20),wardId=dedicated?d.ward_id:(text(v.wardId,64)||d.ward_id),selectedWard=await env.DB.prepare('SELECT id FROM wards WHERE id=? AND facility_id=? AND active=1').bind(wardId,d.facility_id).first(),requested=dedicated?[d.assigned_resident_id].filter(Boolean):(Array.isArray(v.residentIds)?[...new Set(v.residentIds.filter(x=>typeof x==='string'))]:[]);if(dedicated&&!d.assigned_resident_id)return fail('This dedicated tablet is not assigned.',409);if(!selectedWard)return fail('Choose an active ward in this facility.',400);if(!['individual','group'].includes(mode))return fail('Choose an individual or group session.');const available=(await env.DB.prepare('SELECT id FROM residents WHERE facility_id=? AND ward_id=? AND active=1').bind(d.facility_id,selectedWard.id).all()).results.map(x=>x.id),availableSet=new Set(available),anonymous=!dedicated&&available.length===0;if(!anonymous&&mode==='individual'&&requested.length!==1)return fail('Choose one resident for an individual session.');if(!anonymous&&mode==='group'&&requested.length<2)return fail('Choose at least two residents for a group session.');if(requested.some(x=>!availableSet.has(x)))return fail('One or more selected residents are unavailable.');const sessionId=id(),startedAt=now(),writes=[env.DB.prepare("UPDATE activity_sessions SET status='ended',ended_at=? WHERE device_id=? AND status='active'").bind(startedAt,d.id),env.DB.prepare('INSERT INTO activity_sessions (id,facility_id,device_id,ward_id,mode,anonymous,started_at) VALUES (?,?,?,?,?,?,?)').bind(sessionId,d.facility_id,d.id,selectedWard.id,mode,anonymous?1:0,startedAt),...requested.map(residentId=>env.DB.prepare('INSERT INTO activity_session_residents (session_id,resident_id) VALUES (?,?)').bind(sessionId,residentId))];await env.DB.batch(writes);return json({id:sessionId,mode,anonymous,startedAt,residentIds:requested},201);}
 if(url.pathname==='/api/device/sessions/end'&&request.method==='POST'){const d=await device(request,env),v=await input(request),sessionId=text(v.sessionId,64),observations=Array.isArray(v.observations)?v.observations:[];if(!sessionId)return fail('Choose an active session.');const session=await env.DB.prepare("SELECT id,anonymous FROM activity_sessions WHERE id=? AND device_id=? AND status='active'").bind(sessionId,d.id).first();if(!session)return fail('This session is no longer active.',409);const participantIds=(await env.DB.prepare('SELECT resident_id FROM activity_session_residents WHERE session_id=?').bind(sessionId).all()).results.map(x=>x.resident_id),expected=session.anonymous?[null]:participantIds;if(observations.length!==expected.length)return fail('Record an observation for each participant before ending the session.');const writes=[];for(const observation of observations){const residentId=observation.residentId||null,engagement=Number(observation.engagementLevel),change=observation.wellbeingChange,tags=Array.isArray(observation.outcomeTags)?[...new Set(observation.outcomeTags.filter(x=>outcomeTags.includes(x)))]:[];if(!expected.includes(residentId)||!Number.isInteger(engagement)||engagement<1||engagement>5||!wellbeingChanges.includes(change))return fail('One or more session observations are invalid.');writes.push(env.DB.prepare('INSERT INTO session_outcomes (id,session_id,resident_id,engagement_level,wellbeing_change,outcome_tags_json) VALUES (?,?,?,?,?,?)').bind(id(),sessionId,residentId,engagement,change,JSON.stringify(tags)));}writes.push(env.DB.prepare("UPDATE activity_sessions SET status='ended',ended_at=? WHERE id=? AND device_id=? AND status='active'").bind(now(),sessionId,d.id));await env.DB.batch(writes);return json({id:sessionId,status:'ended'});}
 if(url.pathname==='/api/device/events'&&request.method==='POST'){const d=await device(request,env);if(d.status!=='active'||d.licence_status!=='active')return fail('This device is not active.',403);if(!d.ward_id)return fail('This device must be assigned to a ward.',403);const events=(await input(request)).events;if(!Array.isArray(events)||!events.length||events.length>100)return fail('Send between 1 and 100 events.');const writes=[];for(const e of events){if(!/^[a-zA-Z0-9-]{16,64}$/.test(e.id||'')||!text(e.feature,80)||!text(e.eventName,80)||!Number.isFinite(Number(e.durationSeconds))||Number(e.durationSeconds)<0||Number(e.durationSeconds)>86400||Number.isNaN(Date.parse(e.occurredAt)))return fail('One or more usage events are invalid.');if(e.sessionId){const session=await env.DB.prepare("SELECT id FROM activity_sessions WHERE id=? AND device_id=? AND status='active'").bind(e.sessionId,d.id).first();if(!session)return fail('A usage event references an inactive session.');}writes.push(env.DB.prepare('INSERT OR IGNORE INTO usage_events (id,facility_id,device_id,ward_id,resident_id,session_id,feature,event_name,duration_seconds,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(e.id,d.facility_id,d.id,d.ward_id,null,e.sessionId||null,e.feature.trim(),e.eventName.trim(),Math.floor(Number(e.durationSeconds)),new Date(e.occurredAt).toISOString()));}await env.DB.batch(writes);await env.DB.prepare('UPDATE devices SET last_seen_at=? WHERE id=?').bind(now(),d.id).run();return json({accepted:events.length},202);}
 if(url.pathname==='/api/device/profile-forms'&&request.method==='GET'){const d=await device(request,env),formId=text(url.searchParams.get('formId'),80),residentId=await deviceResident(env,d);if(!formId||!/^[a-z0-9_-]+$/i.test(formId))return fail('Choose a valid profile form.');if(!residentId)return fail('Start an individual resident session first.',409);const row=await env.DB.prepare('SELECT data_cipher,updated_at FROM resident_profile_forms WHERE facility_id=? AND resident_id=? AND form_id=?').bind(d.facility_id,residentId,formId).first();if(!row)return json({formId,data:{},updatedAt:null});let data={};try{data=JSON.parse(await decrypt(env,row.data_cipher));}catch{return fail('The saved profile form could not be read.',500);}return json({formId,data,updatedAt:row.updated_at});}
 if(url.pathname==='/api/device/profile-forms'&&request.method==='POST'){const d=await device(request,env),v=await input(request),formId=text(v.formId,80),residentId=await deviceResident(env,d);if(!formId||!/^[a-z0-9_-]+$/i.test(formId)||!v.data||typeof v.data!=='object'||Array.isArray(v.data))return fail('Choose a valid profile form and data.');if(!residentId)return fail('Start an individual resident session first.',409);const serialised=JSON.stringify(v.data);if(serialised.length>50000)return fail('This profile form is too large.',413);const updatedAt=now();await env.DB.prepare('INSERT INTO resident_profile_forms (facility_id,resident_id,form_id,data_cipher,updated_by,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(facility_id,resident_id,form_id) DO UPDATE SET data_cipher=excluded.data_cipher,updated_by=excluded.updated_by,updated_at=excluded.updated_at').bind(d.facility_id,residentId,formId,await encrypt(env,serialised),`device:${d.id}`,updatedAt).run();return json({formId,updatedAt});}
 if(url.pathname==='/api/device/commands/ack'&&request.method==='POST'){const d=await device(request,env),v=await input(request),commandId=text(v.commandId,64),status=['completed','failed'].includes(v.status)?v.status:null;if(!commandId||!status)return fail('Choose a command and completion status.');const command=await env.DB.prepare("SELECT id,command FROM device_commands WHERE id=? AND device_id=? AND status='pending'").bind(commandId,d.id).first();if(!command)return fail('This device command is no longer pending.',409);const completedAt=now(),writes=[env.DB.prepare('UPDATE device_commands SET status=?,acknowledged_at=?,completed_at=? WHERE id=? AND device_id=?').bind(status,completedAt,completedAt,commandId,d.id)];if(command.command==='privacy_reset'&&status==='completed'){writes.push(env.DB.prepare("UPDATE devices SET lifecycle_state='ready' WHERE id=? AND facility_id=? AND assigned_resident_id IS NULL").bind(d.id,d.facility_id),env.DB.prepare('UPDATE device_assignments SET privacy_reset_at=? WHERE device_id=? AND ended_at IS NOT NULL AND privacy_reset_at IS NULL').bind(completedAt,d.id));}await env.DB.batch(writes);return json({id:commandId,status});}
 const user=await userFor(request,env);
 if(url.pathname==='/api/admin/resources'||url.pathname.startsWith('/api/admin/resources/'))return adminResources(request,env,user);
 if(url.pathname==='/api/me'&&request.method==='GET')return json({email:user.email,role:user.role,facilityId:user.facility_id,facilityName:user.facility_name,wardId:user.ward_id,wardName:user.ward_name});
 if(url.pathname==='/api/admin/portal-auth-cutover'&&request.method==='POST'){sameOrigin(request);permitted(user,r=>r==='truselv_admin');const apps=await cloudflare(env,'/access/apps?per_page=100'),app=apps.find(x=>x.domain===env.PORTAL_HOST);if(!app)return fail('The portal Access application could not be found.',503);const policies=await cloudflare(env,`/access/apps/${app.id}/policies?per_page=100`),existing=policies.find(x=>x.name==='TruSelv facility sign-in'&&x.decision==='bypass');if(existing)return json({enabled:true,policyId:existing.id});const precedence=Math.max(0,...policies.map(x=>Number(x.precedence)||0))+1,policy=await cloudflare(env,`/access/apps/${app.id}/policies`,{method:'POST',body:JSON.stringify({name:'TruSelv facility sign-in',decision:'bypass',include:[{everyone:{}}],precedence})});await audit(env,user,'portal.authentication.enabled','access_policy',policy.id,{host:env.PORTAL_HOST});return json({enabled:true,policyId:policy.id});}
 if(url.pathname==='/api/admin/portfolio'&&request.method==='GET'){permitted(user,r=>r==='truselv_admin');const rows=await env.DB.prepare("SELECT f.id,f.name,f.status,f.created_at,(SELECT COUNT(*) FROM devices d WHERE d.facility_id=f.id AND d.status='active') active_devices,(SELECT COUNT(*) FROM licences l WHERE l.facility_id=f.id AND l.status='active') active_licences,(SELECT COUNT(*) FROM usage_events u WHERE u.facility_id=f.id AND u.occurred_at>=datetime('now','-30 days')) interactions_30d,(SELECT COUNT(*) FROM activity_sessions s WHERE s.facility_id=f.id AND s.started_at>=datetime('now','-30 days')) sessions_30d,(SELECT MAX(u.occurred_at) FROM usage_events u WHERE u.facility_id=f.id) last_activity_at FROM facilities f ORDER BY CASE f.status WHEN 'active' THEN 0 WHEN 'pending' THEN 1 ELSE 2 END, lower(f.name)").all();return json({facilities:rows.results});}
 if(url.pathname==='/api/admin/marketing'&&request.method==='GET'){permitted(user,r=>r==='truselv_admin');const segmentId=await marketingSegment(env),result=await resend(env,`/segments/${encodeURIComponent(segmentId)}/contacts?limit=100`),contacts=result.data||result.contacts||[];return json({configured:true,contacts:contacts.map(x=>({id:x.id,email:x.email,firstName:x.first_name||x.firstName||'',lastName:x.last_name||x.lastName||'',unsubscribed:Boolean(x.unsubscribed),createdAt:x.created_at||x.createdAt||null})),hasMore:Boolean(result.has_more)});}
 if(url.pathname==='/api/admin/marketing/test'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),subject=text(v.subject,150),message=text(v.message,10000),linkUrl=text(v.linkUrl,1000),linkLabel=text(v.linkLabel,80);if(!subject||!message)return fail('Enter a subject and message.');if(linkUrl&&!/^https:\/\//i.test(linkUrl))return fail('The button link must begin with https://');const preview=marketingHtml(message,linkUrl,linkLabel).replaceAll('{{{FIRST_NAME|there}}}','TruSelv admin').replaceAll('{{{RESEND_UNSUBSCRIBE_URL}}}','https://truselv.co.uk/privacy');const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`marketing-test/${id()}`},body:JSON.stringify({from:env.MARKETING_FROM||env.PORTAL_INVITE_FROM,to:[user.email],subject:`[TEST] ${subject}`,html:preview}),signal:AbortSignal.timeout(15000)});if(!response.ok)return fail('The test email could not be sent.',502);await audit(env,user,'marketing.test_sent','broadcast',null,{subject});return json({sentTo:user.email});}
 if(url.pathname==='/api/admin/marketing/broadcast'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),subject=text(v.subject,150),message=text(v.message,10000),linkUrl=text(v.linkUrl,1000),linkLabel=text(v.linkLabel,80),action=['draft','send','schedule'].includes(v.action)?v.action:null,scheduledAt=text(v.scheduledAt,40);if(!subject||!message||!action)return fail('Enter a subject and message, then choose an action.');if(linkUrl&&!/^https:\/\//i.test(linkUrl))return fail('The button link must begin with https://');if(action==='schedule'&&(!scheduledAt||Number.isNaN(Date.parse(scheduledAt))||Date.parse(scheduledAt)<=Date.now()))return fail('Choose a future date and time.');const payload={segment_id:await marketingSegment(env),from:env.MARKETING_FROM||env.PORTAL_INVITE_FROM,subject,html:marketingHtml(message,linkUrl,linkLabel)};if(action!=='draft')payload.send=true;if(action==='schedule')payload.scheduled_at=new Date(scheduledAt).toISOString();const created=await resend(env,'/broadcasts',{method:'POST',body:JSON.stringify(payload)});await audit(env,user,`marketing.broadcast_${action}`,'broadcast',created.id||null,{subject,scheduledAt:payload.scheduled_at||null});return json({id:created.id,status:action==='draft'?'draft':action==='schedule'?'scheduled':'queued'});}
 if(url.pathname==='/api/facilities'&&request.method==='GET'){permitted(user,r=>r==='truselv_admin');return json({facilities:(await env.DB.prepare('SELECT id,name,plan,status,created_at FROM facilities ORDER BY name').all()).results});}
 if(url.pathname==='/api/facilities'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),name=text(v.name,150),plan=['standard','organisation','dedicated'].includes(v.plan)?v.plan:'organisation';if(!name)return fail('An organisation name is required.');const facilityId=id();await env.DB.prepare("INSERT INTO facilities (id,name,status,plan) VALUES (?,?,'pending',?)").bind(facilityId,name,plan).run();await audit(env,user,'facility.created','facility',facilityId,{name,plan});return json({id:facilityId,name,plan,status:'pending'},201);}
 if(url.pathname==='/api/facilities/update'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),facilityId=text(v.facilityId,64),name=text(v.name,150),plan=['standard','organisation','dedicated'].includes(v.plan)?v.plan:null,status=['pending','active','suspended'].includes(v.status)?v.status:null;if(!facilityId||!name||!plan||!status)return fail('Choose an organisation, plan and status.');const existing=await env.DB.prepare('SELECT id,status FROM facilities WHERE id=?').bind(facilityId).first();if(!existing)return fail('Organisation not found.',404);if(existing.status==='active'&&status==='pending')return fail('An active organisation cannot return to pending.',409);await env.DB.prepare('UPDATE facilities SET name=?,plan=?,status=? WHERE id=?').bind(name,plan,status,facilityId).run();await audit(env,user,'facility.updated','facility',facilityId,{name,plan,status,previousStatus:existing.status});return json({id:facilityId,name,plan,status});}
 if(url.pathname==='/api/support/tickets'&&request.method==='GET'){const admin=user.role==='truselv_admin',wanted=url.searchParams.get('facilityId');if(!admin&&wanted&&wanted!==user.facility_id)return fail('Facility access denied.',403);const facilityFilter=admin?wanted:user.facility_id,where=facilityFilter?'WHERE t.facility_id=?':'',args=facilityFilter?[facilityFilter]:[];const tickets=(await env.DB.prepare(`SELECT t.*,f.name facility_name,(SELECT COUNT(*) FROM support_ticket_messages m WHERE m.ticket_id=t.id AND (m.visible_to_facility=1 OR ?=1)) message_count FROM support_tickets t JOIN facilities f ON f.id=t.facility_id ${where} ORDER BY CASE t.status WHEN 'new' THEN 0 WHEN 'open' THEN 1 WHEN 'waiting' THEN 2 WHEN 'resolved' THEN 3 ELSE 4 END,t.updated_at DESC LIMIT 500`).bind(admin?1:0,...args).all()).results;let messages=[];const ticketId=text(url.searchParams.get('ticketId'),64);if(ticketId){const ticket=tickets.find(x=>x.id===ticketId);if(!ticket)return fail('Ticket not found.',404);messages=(await env.DB.prepare(`SELECT id,author_email,author_role,message,visible_to_facility,created_at FROM support_ticket_messages WHERE ticket_id=?${admin?'':' AND visible_to_facility=1'} ORDER BY created_at`).bind(ticketId).all()).results;}return json({tickets,messages,categories:ticketCategories,statuses:ticketStatuses,priorities:ticketPriorities});}
 if(url.pathname==='/api/support/tickets'&&request.method==='POST'){const v=await input(request),category=text(v.category,40),subject=text(v.subject,150),description=text(v.description,5000),priority=ticketPriorities.includes(v.priority)?v.priority:'normal',facilityId=user.role==='truselv_admin'?text(v.facilityId,64):user.facility_id;if(!facilityId||!ticketCategories.includes(category)||!subject||!description)return fail('Choose a category and enter a subject and description.');const facility=await env.DB.prepare("SELECT id,name FROM facilities WHERE id=? AND status='active'").bind(facilityId).first();if(!facility)return fail('Choose an active facility.',400);const ticketId=id(),reference=ticketReference();await env.DB.prepare('INSERT INTO support_tickets (id,reference,facility_id,requester_user_id,requester_email,category,subject,description,priority) VALUES (?,?,?,?,?,?,?,?,?)').bind(ticketId,reference,facilityId,user.id,user.email,category,subject,description,priority).run();await audit(env,user,'support.ticket.created','support_ticket',ticketId,{reference,category,priority});const emailSent=await sendMail(env,{to:env.SUPPORT_INBOX||'support@truselv.co.uk',subject:`[${reference}] ${facility.name}: ${subject}`,idempotencyKey:`tess-support-new/${ticketId}`,text:`New TESS support request\n\nReference: ${reference}\nFacility: ${facility.name}\nFrom: ${user.email}\nCategory: ${category.replaceAll('-',' ')}\nPriority: ${priority}\n\n${description}\n\nManage this request at https://admin.truselv.co.uk`});return json({id:ticketId,reference,status:'new',emailSent},201);}
 if(url.pathname==='/api/support/tickets/update'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),ticketId=text(v.ticketId,64),status=text(v.status,20),priority=text(v.priority,20),assignedTo=text(v.assignedTo,254),resolution=typeof v.resolution==='string'?v.resolution.trim().slice(0,3000):'';if(!ticketId||!ticketStatuses.includes(status)||!ticketPriorities.includes(priority))return fail('Choose a valid ticket status and priority.');const ticket=await env.DB.prepare('SELECT t.*,f.name facility_name FROM support_tickets t JOIN facilities f ON f.id=t.facility_id WHERE t.id=?').bind(ticketId).first();if(!ticket)return fail('Ticket not found.',404);const resolvedAt=['resolved','closed'].includes(status)?(ticket.resolved_at||now()):null;await env.DB.prepare('UPDATE support_tickets SET status=?,priority=?,assigned_to=?,resolution=?,resolved_at=?,updated_at=? WHERE id=?').bind(status,priority,assignedTo||null,resolution||null,resolvedAt,now(),ticketId).run();await audit(env,user,'support.ticket.updated','support_ticket',ticketId,{status,priority,assignedTo:assignedTo||null});await sendMail(env,{to:ticket.requester_email,subject:`[${ticket.reference}] Support request updated`,idempotencyKey:`tess-support-update/${ticketId}/${id()}`,text:`Hello,\n\nYour TESS support request has been updated.\n\nReference: ${ticket.reference}\nFacility: ${ticket.facility_name}\nStatus: ${status}\nPriority: ${priority}${resolution?`\nResolution: ${resolution}`:''}\n\nYou can view the request at https://${env.PORTAL_HOST}\n\nTruSelv Support`});return json({id:ticketId,status,priority});}
 if(url.pathname==='/api/support/tickets/reply'&&request.method==='POST'){const v=await input(request),ticketId=text(v.ticketId,64),message=text(v.message,3000);if(!ticketId||!message)return fail('Enter a reply.');const ticket=await env.DB.prepare('SELECT t.*,f.name facility_name FROM support_tickets t JOIN facilities f ON f.id=t.facility_id WHERE t.id=?').bind(ticketId).first();if(!ticket||(user.role!=='truselv_admin'&&ticket.facility_id!==user.facility_id))return fail('Ticket not found.',404);const visible=user.role==='truselv_admin'?v.visibleToFacility!==false:true,nextStatus=user.role==='truselv_admin'?(visible?'waiting':ticket.status):'open';await env.DB.batch([env.DB.prepare('INSERT INTO support_ticket_messages (id,ticket_id,author_email,author_role,message,visible_to_facility) VALUES (?,?,?,?,?,?)').bind(id(),ticketId,user.email,user.role,message,visible?1:0),env.DB.prepare('UPDATE support_tickets SET status=?,updated_at=? WHERE id=?').bind(nextStatus,now(),ticketId)]);await audit(env,user,'support.ticket.replied','support_ticket',ticketId,{visibleToFacility:visible});if(visible){const recipient=user.role==='truselv_admin'?ticket.requester_email:(env.SUPPORT_INBOX||'support@truselv.co.uk');await sendMail(env,{to:recipient,subject:`[${ticket.reference}] New support reply`,idempotencyKey:`tess-support-reply/${ticketId}/${id()}`,text:`New reply for ${ticket.reference}\nFacility: ${ticket.facility_name}\nFrom: ${user.email}\n\n${message}\n\nView the request at ${user.role==='truselv_admin'?`https://${env.PORTAL_HOST}`:'https://admin.truselv.co.uk'}`});}return json({id:ticketId,status:nextStatus});}
 const facilityId=scope(user,url.searchParams.get('facilityId'));
 if(url.pathname==='/api/configuration'&&request.method==='GET'){permitted(user,r=>manage(r)||facilityStructure(r));if(!facilityId)return fail('Choose a facility.',400);const facility=await env.DB.prepare('SELECT id,name,plan,terminology_person,terminology_unit FROM facilities WHERE id=?').bind(facilityId).first(),published=await env.DB.prepare("SELECT id,version,schema_version,status,config_json,change_summary,created_by,approved_by,created_at,published_at FROM organisation_config_versions WHERE facility_id=? AND status='published' ORDER BY version DESC LIMIT 1").bind(facilityId).first(),drafts=(await env.DB.prepare("SELECT id,version,schema_version,status,config_json,change_summary,created_by,created_at FROM organisation_config_versions WHERE facility_id=? AND status='draft' ORDER BY version DESC LIMIT 20").bind(facilityId).all()).results;return json({facility,published:published?{...published,config:JSON.parse(published.config_json)}:null,drafts:drafts.map(row=>({...row,config:JSON.parse(row.config_json)})),featureIds:configurableFeatures});}
 if(url.pathname==='/api/configuration/draft'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),facility=await env.DB.prepare('SELECT id,name,plan,terminology_person,terminology_unit FROM facilities WHERE id=?').bind(f).first();if(!facility)return fail('Choose a facility.',400);const config=validatedOrganisationConfig(v.config,facility),latest=await env.DB.prepare('SELECT MAX(version) version FROM organisation_config_versions WHERE facility_id=?').bind(f).first(),version=(Number(latest?.version)||0)+1,configId=id(),summary=text(v.changeSummary,500)||'Organisation configuration updated';await env.DB.prepare('INSERT INTO organisation_config_versions (id,facility_id,version,schema_version,status,config_json,change_summary,created_by) VALUES (?,?,?,?,?,?,?,?)').bind(configId,f,version,1,'draft',JSON.stringify(config),summary,user.email).run();await audit(env,user,'configuration.draft_created','organisation_config',configId,{facilityId:f,version});return json({id:configId,version,status:'draft',config},201);}
 if(url.pathname==='/api/configuration/publish'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),configId=text(v.configId,64),draft=await env.DB.prepare("SELECT id,version FROM organisation_config_versions WHERE id=? AND facility_id=? AND status='draft'").bind(configId,f).first();if(!draft)return fail('Choose an unpublished configuration.',404);const publishedAt=now();await env.DB.batch([env.DB.prepare("UPDATE organisation_config_versions SET status='superseded' WHERE facility_id=? AND status='published'").bind(f),env.DB.prepare("UPDATE organisation_config_versions SET status='published',approved_by=?,published_at=? WHERE id=? AND facility_id=? AND status='draft'").bind(user.email,publishedAt,configId,f),env.DB.prepare("INSERT INTO device_commands (id,facility_id,device_id,command,payload_json,status,created_by) SELECT lower(hex(randomblob(16))),facility_id,id,'refresh_config','{}','pending',? FROM devices WHERE facility_id=? AND status='active'").bind(user.email,f)]);await audit(env,user,'configuration.published','organisation_config',configId,{facilityId:f,version:draft.version});return json({id:configId,version:draft.version,status:'published',publishedAt});}
 if(url.pathname==='/api/wards'&&request.method==='GET'){permitted(user,r=>manage(r)||facilityStructure(r)||r==='ward_analytics');if(!facilityId)return fail('Choose a facility.',400);const own=user.role==='ward_analytics'?' AND id=?':'';const result=await env.DB.prepare(`SELECT id,name,active,created_at FROM wards WHERE facility_id=?${own} ORDER BY name`).bind(facilityId,...(own?[user.ward_id]:[])).all();return json({wards:result.results});}
 if(url.pathname==='/api/wards'&&request.method==='POST'){permitted(user,facilityStructure);const name=text((await input(request)).name,100);if(!facilityId||!name)return fail('A facility and ward name are required.');const wardId=id();await env.DB.prepare('INSERT INTO wards (id,facility_id,name) VALUES (?,?,?)').bind(wardId,facilityId,name).run();await audit(env,user,'ward.created','ward',wardId,{name});return json({id:wardId,name},201);}
 if(url.pathname==='/api/dashboard'&&request.method==='GET'){if(!facilityId)return fail('Choose a facility.',400);const w=await wardScope(env,user,facilityId,url.searchParams.get('wardId'));return json(await dashboard(env,facilityId,w?.id,residents(user.role)));}
 if(url.pathname==='/api/analytics'&&request.method==='GET'){if(!facilityId)return fail('Choose a facility.',400);const w=await wardScope(env,user,facilityId,url.searchParams.get('wardId'));return analytics(env,facilityId,w?.id,user,url);}
 if(url.pathname==='/api/devices'&&request.method==='GET'){
  permitted(user,manage);
  if(!facilityId)return fail('Choose a facility.',400);
  const rows=await env.DB.prepare("SELECT d.id,d.label,d.platform,d.status,d.last_seen_at,d.app_version,d.licence_id,w.name ward_name,d.ward_id,d.created_at,d.ownership,d.device_mode,d.assigned_resident_id,d.lifecycle_state,d.configuration_version,ls.id seat_id,ls.seat_number,r.first_name_cipher,r.last_name_cipher FROM devices d JOIN wards w ON w.id=d.ward_id LEFT JOIN licence_seats ls ON ls.device_id=d.id LEFT JOIN residents r ON r.id=d.assigned_resident_id WHERE d.facility_id=? ORDER BY d.created_at DESC").bind(facilityId).all();
  const devices=await Promise.all(rows.results.map(async row=>{
   const assignedResidentName=row.assigned_resident_id?`${await decrypt(env,row.first_name_cipher)} ${await decrypt(env,row.last_name_cipher)}`.trim():null;
   const {first_name_cipher,last_name_cipher,...safe}=row;
   return {...safe,assigned_resident_name:assignedResidentName};
  }));
  return json({devices});
 }
 if(url.pathname==='/api/devices'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),label=text(v.label,100),licenceId=text(v.licenceId,64),deviceMode=v.deviceMode==='dedicated'?'dedicated':'shared',ownership=v.ownership==='truselv_supplied'?'truselv_supplied':'customer_owned';if(!f||!label||!licenceId)return fail('Facility, ward, device label and licence are required.');const w=await ward(env,f,v.wardId,true),licence=await env.DB.prepare("SELECT id FROM licences WHERE id=? AND facility_id=? AND status='active' AND (ends_on IS NULL OR ends_on>=date('now'))").bind(licenceId,f).first();if(!licence)return fail('Choose an active facility licence.');const seat=await env.DB.prepare("SELECT id,seat_number FROM licence_seats WHERE licence_id=? AND facility_id=? AND status='available' AND device_id IS NULL ORDER BY seat_number LIMIT 1").bind(licenceId,f).first();if(!seat)return fail('Every licence seat is already assigned. Add or release a device licence.',409);const deviceId=id(),key=b64(crypto.getRandomValues(new Uint8Array(32))),createdAt=now(),results=await env.DB.batch([env.DB.prepare('INSERT INTO devices (id,facility_id,ward_id,licence_id,label,activation_token_hash,ownership,device_mode,lifecycle_state) VALUES (?,?,?,?,?,?,?,?,?)').bind(deviceId,f,w.id,licenceId,label,await digest(key),ownership,deviceMode,'ready'),env.DB.prepare("UPDATE licence_seats SET device_id=?,status='assigned',assigned_at=?,released_at=NULL WHERE id=? AND status='available' AND device_id IS NULL").bind(deviceId,createdAt,seat.id)]);if(Number(results[1]?.meta?.changes)!==1){await env.DB.prepare('DELETE FROM devices WHERE id=?').bind(deviceId).run();return fail('That licence seat was just assigned elsewhere. Please try again.',409);}await audit(env,user,'device.created','device',deviceId,{label,wardId:w.id,deviceMode,ownership,seatId:seat.id});return json({id:deviceId,label,deviceKey:key,seatNumber:seat.seat_number,notice:'Copy this device key now. It cannot be viewed again.'},201);}
 if(url.pathname==='/api/devices/assign'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),deviceId=text(v.deviceId,64),residentId=text(v.residentId,64),deviceRow=await env.DB.prepare("SELECT id,ward_id,assigned_resident_id,lifecycle_state FROM devices WHERE id=? AND facility_id=? AND status!='retired'").bind(deviceId,f).first(),resident=await env.DB.prepare('SELECT id,ward_id FROM residents WHERE id=? AND facility_id=? AND active=1').bind(residentId,f).first();if(!deviceRow||!resident)return fail('Choose an active device and resident.',404);if(deviceRow.assigned_resident_id)return fail('End the existing resident assignment first.',409);if(deviceRow.lifecycle_state==='privacy_reset_pending')return fail('Wait for this tablet to complete its privacy reset before assigning another resident.',409);const assignmentId=id(),assignedAt=now();await env.DB.batch([env.DB.prepare("UPDATE devices SET device_mode='dedicated',assigned_resident_id=?,ward_id=?,lifecycle_state='assigned' WHERE id=? AND facility_id=?").bind(resident.id,resident.ward_id,deviceId,f),env.DB.prepare('INSERT INTO device_assignments (id,facility_id,device_id,resident_id,assigned_by,started_at) VALUES (?,?,?,?,?,?)').bind(assignmentId,f,deviceId,resident.id,user.email,assignedAt),env.DB.prepare("INSERT INTO device_commands (id,facility_id,device_id,command,payload_json,status,created_by) VALUES (?,?,?,?,?,'pending',?)").bind(id(),f,deviceId,'refresh_config',JSON.stringify({assignedResidentId:resident.id}),user.email)]);await audit(env,user,'device.resident_assigned','device',deviceId,{residentId:resident.id,assignmentId});return json({deviceId,residentId:resident.id,assignmentId,status:'assigned'});}
 if(url.pathname==='/api/devices/unassign'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),deviceId=text(v.deviceId,64),reason=['reassigned','discharged','deceased','device_replaced','other'].includes(v.reason)?v.reason:'other',deviceRow=await env.DB.prepare("SELECT id,assigned_resident_id FROM devices WHERE id=? AND facility_id=? AND device_mode='dedicated' AND assigned_resident_id IS NOT NULL").bind(deviceId,f).first();if(!deviceRow)return fail('This device has no active resident assignment.',409);const endedAt=now(),commandId=id();await env.DB.batch([env.DB.prepare("UPDATE activity_sessions SET status='ended',ended_at=? WHERE device_id=? AND status='active'").bind(endedAt,deviceId),env.DB.prepare("UPDATE device_assignments SET ended_at=?,ended_by=?,ended_reason=? WHERE device_id=? AND ended_at IS NULL").bind(endedAt,user.email,reason,deviceId),env.DB.prepare("UPDATE devices SET assigned_resident_id=NULL,lifecycle_state='privacy_reset_pending' WHERE id=? AND facility_id=?").bind(deviceId,f),env.DB.prepare("INSERT INTO device_commands (id,facility_id,device_id,command,payload_json,status,created_by) VALUES (?,?,?,?,?,'pending',?)").bind(commandId,f,deviceId,'privacy_reset',JSON.stringify({reason,residentId:deviceRow.assigned_resident_id}),user.email)]);await audit(env,user,'device.resident_unassigned','device',deviceId,{residentId:deviceRow.assigned_resident_id,reason,commandId});return json({deviceId,status:'privacy_reset_pending',commandId});}
 if(url.pathname==='/api/devices/release'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),deviceId=text(v.deviceId,64),deviceRow=await env.DB.prepare('SELECT id,assigned_resident_id FROM devices WHERE id=? AND facility_id=?').bind(deviceId,f).first();if(!deviceRow)return fail('Device not found.',404);if(deviceRow.assigned_resident_id)return fail('End the resident assignment before releasing this device.',409);const releasedAt=now();await env.DB.batch([env.DB.prepare("UPDATE devices SET status='retired',lifecycle_state='retired' WHERE id=? AND facility_id=?").bind(deviceId,f),env.DB.prepare("UPDATE licence_seats SET device_id=NULL,status='available',released_at=? WHERE device_id=? AND facility_id=?").bind(releasedAt,deviceId,f)]);await audit(env,user,'device.released','device',deviceId,{facilityId:f});return json({deviceId,status:'retired',seatReleased:true});}
 if(url.pathname==='/api/licences'&&request.method==='GET'){permitted(user,manage);const select="SELECT l.id,l.facility_id,l.status,l.seats,l.starts_on,l.ends_on,l.created_at,(SELECT COUNT(*) FROM licence_seats s WHERE s.licence_id=l.id AND s.device_id IS NOT NULL) seats_used,(SELECT COUNT(*) FROM licence_seats s WHERE s.licence_id=l.id AND s.status='available' AND s.device_id IS NULL) seats_available";if(url.searchParams.get('all')==='1'){permitted(user,r=>r==='truselv_admin');return json({licences:(await env.DB.prepare(`${select},f.name facility_name FROM licences l JOIN facilities f ON f.id=l.facility_id ORDER BY l.created_at DESC`).all()).results});}if(!facilityId)return fail('Choose a facility.',400);return json({licences:(await env.DB.prepare(`${select} FROM licences l WHERE l.facility_id=? ORDER BY l.created_at DESC`).bind(facilityId).all()).results});}
 if(url.pathname==='/api/licences'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),f=text(v.facilityId,64),seats=Number(v.seats),starts=text(v.startsOn,10),ends=text(v.endsOn,10);if(!f||!Number.isInteger(seats)||seats<1||seats>10000||!/^\d{4}-\d{2}-\d{2}$/.test(starts||''))return fail('A facility, seat count and start date are required.');const licenceId=id(),writes=[env.DB.prepare('INSERT INTO licences (id,facility_id,seats,starts_on,ends_on) VALUES (?,?,?,?,?)').bind(licenceId,f,seats,starts,ends),...Array.from({length:seats},(_,index)=>env.DB.prepare("INSERT INTO licence_seats (id,licence_id,facility_id,seat_number,status) VALUES (?,?,?,?, 'available')").bind(id(),licenceId,f,index+1))];await env.DB.batch(writes);await audit(env,user,'licence.created','licence',licenceId,{facilityId:f,seats});return json({id:licenceId,seats},201);}
 if(url.pathname==='/api/licences/revoke'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),f=text(v.facilityId,64),licenceId=text(v.licenceId,64);if(!f||!licenceId)return fail('Choose a facility licence.',400);const licence=await env.DB.prepare('SELECT id,status FROM licences WHERE id=? AND facility_id=?').bind(licenceId,f).first();if(!licence)return fail('Licence not found.',404);if(licence.status!=='active')return fail('This licence is already inactive.',409);await env.DB.prepare("UPDATE licences SET status='suspended' WHERE id=?").bind(licenceId).run();await audit(env,user,'licence.revoked','licence',licenceId,{facilityId:f});return json({id:licenceId,status:'suspended'});}
 if(url.pathname==='/api/residents'&&request.method==='GET'){permitted(user,facilityStructure);if(!facilityId)return fail('Choose a facility.',400);const w=await wardScope(env,user,facilityId,url.searchParams.get('wardId'));const filter=w?' AND ward_id=?':'',rows=(await env.DB.prepare(`SELECT id,first_name_cipher,last_name_cipher,dob_cipher,active,created_at FROM residents WHERE facility_id=?${filter} ORDER BY created_at DESC`).bind(facilityId,...(w?[w.id]:[])).all()).results;return json({residents:await Promise.all(rows.map(async r=>({id:r.id,firstName:await decrypt(env,r.first_name_cipher),lastName:await decrypt(env,r.last_name_cipher),dateOfBirth:await decrypt(env,r.dob_cipher),active:Boolean(r.active),createdAt:r.created_at})))});}
 if(url.pathname==='/api/residents/bulk'&&request.method==='POST'){permitted(user,facilityStructure);const v=await input(request),f=scope(user,v.facilityId),items=Array.isArray(v.residents)?v.residents:[];if(!f||!items.length||items.length>200)return fail('Upload between 1 and 200 residents at a time.');const wards=(await env.DB.prepare('SELECT id,name FROM wards WHERE facility_id=? AND active=1').bind(f).all()).results,wardNames=new Map(wards.map(w=>[w.name.trim().toLowerCase(),w])),prepared=[],seen=new Set();for(let index=0;index<items.length;index++){const item=items[index],first=text(item.firstName,100),last=text(item.lastName,100),dob=text(item.dateOfBirth,10),wardName=text(item.ward,100),w=wardNames.get(wardName?.toLowerCase());if(!first||!last||!/^\d{4}-\d{2}-\d{2}$/.test(dob||'')||Number.isNaN(Date.parse(`${dob}T00:00:00Z`))||!w)return fail(`Row ${index+2} has an invalid name, date of birth or ward.`);const key=`${first.trim().toLowerCase()}|${last.trim().toLowerCase()}|${dob}`;if(seen.has(key))return fail(`Row ${index+2} duplicates another resident in this file.`);seen.add(key);prepared.push({first,last,dob,wardId:w.id});}const existing=(await env.DB.prepare('SELECT first_name_cipher,last_name_cipher,dob_cipher FROM residents WHERE facility_id=? AND active=1').bind(f).all()).results,existingKeys=new Set(await Promise.all(existing.map(async r=>`${(await decrypt(env,r.first_name_cipher)).trim().toLowerCase()}|${(await decrypt(env,r.last_name_cipher)).trim().toLowerCase()}|${await decrypt(env,r.dob_cipher)}`))),fresh=prepared.filter(r=>!existingKeys.has(`${r.first.trim().toLowerCase()}|${r.last.trim().toLowerCase()}|${r.dob}`));if(fresh.length){const writes=await Promise.all(fresh.map(async r=>env.DB.prepare('INSERT INTO residents (id,facility_id,ward_id,first_name_cipher,last_name_cipher,dob_cipher) VALUES (?,?,?,?,?,?)').bind(id(),f,r.wardId,await encrypt(env,r.first),await encrypt(env,r.last),await encrypt(env,r.dob))));await env.DB.batch(writes);}await audit(env,user,'residents.bulk_created','facility',f,{uploaded:items.length,created:fresh.length,skipped:items.length-fresh.length});return json({uploaded:items.length,created:fresh.length,skipped:items.length-fresh.length},201);}
 if(url.pathname==='/api/residents'&&request.method==='POST'){permitted(user,facilityStructure);const v=await input(request),f=scope(user,v.facilityId),first=text(v.firstName,100),last=text(v.lastName,100),dob=text(v.dateOfBirth,10);if(!f||!first||!last||!/^\d{4}-\d{2}-\d{2}$/.test(dob||''))return fail('First name, last name and date of birth are required.');const w=await ward(env,f,v.wardId,true),residentId=id();await env.DB.prepare('INSERT INTO residents (id,facility_id,ward_id,first_name_cipher,last_name_cipher,dob_cipher) VALUES (?,?,?,?,?,?)').bind(residentId,f,w.id,await encrypt(env,first),await encrypt(env,last),await encrypt(env,dob)).run();await audit(env,user,'resident.created','resident',residentId);return json({id:residentId},201);}
 if(url.pathname==='/api/users'&&request.method==='GET'){permitted(user,manage);if(!facilityId)return fail('Choose a facility.',400);const rows=await env.DB.prepare('SELECT u.id,u.email,u.role,u.active,u.created_at,w.name ward_name,u.ward_id FROM facility_users u LEFT JOIN wards w ON w.id=u.ward_id WHERE u.facility_id=? ORDER BY u.email').bind(facilityId).all();return json({users:rows.results});}
 if(url.pathname==='/api/users'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase(),role=text(v.role,40);if(!f||!email||!/^\S+@\S+\.\S+$/.test(email)||!roles.includes(role)||role==='truselv_admin')return fail('A valid work email and facility role are required.');const w=role==='ward_analytics'?await ward(env,f,v.wardId,true):null,userId=id();await env.DB.prepare('INSERT INTO facility_users (id,facility_id,ward_id,email,role) VALUES (?,?,?,?,?)').bind(userId,f,w?.id||null,email,role).run();await audit(env,user,'user.provisioned','user',userId,{email,role,wardId:w?.id||null});return json({id:userId,email,role},201);}
 if(url.pathname==='/api/invitations'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase(),role=text(v.role,40);if(!f||!email||!/^\S+@\S+\.\S+$/.test(email)||!roles.includes(role)||role==='truselv_admin')return fail('A valid work email and facility role are required.');const w=role==='ward_analytics'?await ward(env,f,v.wardId,true):null;const facility=await env.DB.prepare('SELECT name FROM facilities WHERE id=? AND status=\'active\'').bind(f).first();if(!facility)return fail('Choose an active facility.',400);const exists=await env.DB.prepare('SELECT id FROM facility_users WHERE facility_id=? AND email=?').bind(f,email).first();if(exists)return fail('This email already has access for this facility.',409);const userId=id();await env.DB.prepare('INSERT INTO facility_users (id,facility_id,ward_id,email,role) VALUES (?,?,?,?,?)').bind(userId,f,w?.id||null,email,role).run();const emailSent=await sendInvitation(env,{email,facilityName:facility.name,role,userId});await audit(env,user,'user.invited','user',userId,{email,role,wardId:w?.id||null,emailSent});return json({id:userId,email,role,portalUrl:`https://${env.PORTAL_HOST}`,emailSent},201);}
 if(url.pathname==='/api/invitations/resend'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase();if(!f||!email)return fail('Choose an authorised email.',400);const facility=await env.DB.prepare('SELECT name FROM facilities WHERE id=? AND status=\'active\'').bind(f).first(),invited=await env.DB.prepare('SELECT id,email,role FROM facility_users WHERE facility_id=? AND email=? AND active=1').bind(f,email).first();if(!facility||!invited)return fail('This email does not have active portal access.',404);if(!await sendInvitation(env,{email:invited.email,facilityName:facility.name,role:invited.role,userId:invited.id,attemptId:id()}))return fail('The invitation email could not be accepted. Check the Resend sender configuration.',502);await audit(env,user,'user.invitation_resent','user',invited.id,{email});return json({email,portalUrl:`https://${env.PORTAL_HOST}`});}
 return fail('Not found.',404);
}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/')){try{if(!['GET','POST'].includes(request.method))return fail('Method not allowed.',405);if(request.method==='POST'&&!url.pathname.startsWith('/api/device/'))sameOrigin(request);return await api(request,env,url);}catch(e){return fail(e.message||'The request could not be completed.',e.status||500);}}return env.ASSETS.fetch(request);}};
