const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(error,status=400)=>json({error},status), id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const roles=['truselv_admin','facility_admin','facility_head','activities_lead','viewer','ward_analytics'];
const ticketCategories=['device','login-access','licence','app-feature','connectivity','resident-records','billing','training','other'];
const ticketStatuses=['new','open','waiting','resolved','closed'],ticketPriorities=['low','normal','high','urgent'];
const manage=r=>['truselv_admin','facility_admin'].includes(r), residents=r=>['truselv_admin','facility_admin','activities_lead'].includes(r);
const text=(v,max)=>typeof v==='string'&&v.trim()&&v.trim().length<=max?v.trim():null;
const b64=b=>btoa(String.fromCharCode(...b));
async function digest(v){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))));}
async function authDigest(env,value){const key=await crypto.subtle.importKey('raw',Uint8Array.from(atob(env.FIELD_ENCRYPTION_KEY),x=>x.charCodeAt(0)),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value))));}
const cookie=(request,name)=>(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(`${name}=`))?.slice(name.length+1)||'';
const sessionCookie=token=>`tess_portal_session=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200`;
const expiredSessionCookie='tess_portal_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0';
function sameOrigin(request){const origin=request.headers.get('Origin');if(origin&&origin!==new URL(request.url).origin)throw Object.assign(Error('Request origin denied.'),{status:403});}
async function secureEqual(left,right){const a=Uint8Array.from(atob(left),x=>x.charCodeAt(0)),b=Uint8Array.from(atob(right),x=>x.charCodeAt(0));if(a.length!==b.length)return false;let difference=0;for(let i=0;i<a.length;i++)difference|=a[i]^b[i];return difference===0;}
async function input(request){if(Number(request.headers.get('content-length')||0)>65536)throw Object.assign(Error('Request is too large.'),{status:413});try{return await request.json();}catch{throw Object.assign(Error('Invalid JSON body.'),{status:400});}}
function permitted(user,test){if(!test(user.role))throw Object.assign(Error('You do not have permission for this action.'),{status:403});}
function scope(user,wanted){if(user.role==='truselv_admin')return wanted;if(!user.facility_id||(wanted&&wanted!==user.facility_id))throw Object.assign(Error('Facility access denied.'),{status:403});return user.facility_id;}
async function userFor(request,env){const portalHost=new URL(request.url).hostname===env.PORTAL_HOST;let user;if(portalHost){const token=cookie(request,'tess_portal_session');if(!token)throw Object.assign(Error('Sign in is required.'),{status:401});user=await env.DB.prepare(`SELECT u.id,u.facility_id,u.ward_id,u.email,u.role,u.active,f.name facility_name,f.status facility_status,w.name ward_name,s.id session_id FROM portal_sessions s JOIN facility_users u ON u.id=s.user_id LEFT JOIN facilities f ON f.id=u.facility_id LEFT JOIN wards w ON w.id=u.ward_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1 LIMIT 1`).bind(await digest(token),now()).first();if(user)await env.DB.prepare('UPDATE portal_sessions SET last_seen_at=? WHERE id=?').bind(now(),user.session_id).run();}else{const email=(request.headers.get(env.ACCESS_HEADER||'Cf-Access-Authenticated-User-Email')||env.DEV_IDENTITY_EMAIL||'').trim().toLowerCase();if(!email)throw Object.assign(Error('Sign in is required.'),{status:401});user=await env.DB.prepare(`SELECT u.id,u.facility_id,u.ward_id,u.email,u.role,u.active,f.name facility_name,f.status facility_status,w.name ward_name FROM facility_users u LEFT JOIN facilities f ON f.id=u.facility_id LEFT JOIN wards w ON w.id=u.ward_id WHERE u.email=? AND u.active=1 LIMIT 1`).bind(email).first();}if(!user||(user.facility_id&&user.facility_status!=='active'))throw Object.assign(Error('Your account does not have active portal access.'),{status:portalHost?401:403});return user;}
async function ward(env,facilityId,wardId,required=false){if(!wardId){if(required)throw Object.assign(Error('Choose a ward.'),{status:400});return null;}const row=await env.DB.prepare('SELECT id,name FROM wards WHERE id=? AND facility_id=? AND active=1').bind(wardId,facilityId).first();if(!row)throw Object.assign(Error('Ward access denied.'),{status:403});return row;}
async function wardScope(env,user,facilityId,wanted,required=false){const selected=user.role==='ward_analytics'?user.ward_id:(wanted||null);if(user.role==='ward_analytics'&&wanted&&wanted!==user.ward_id)throw Object.assign(Error('Ward access denied.'),{status:403});return ward(env,facilityId,selected,required);}
async function audit(env,user,action,type,target,details={}){await env.DB.prepare('INSERT INTO audit_log (id,facility_id,actor_email,action,target_type,target_id,details_json) VALUES (?,?,?,?,?,?,?)').bind(id(),user.facility_id||null,user.email,action,type,target,JSON.stringify(details)).run();}
async function cryptoKey(env){if(!env.FIELD_ENCRYPTION_KEY)throw Object.assign(Error('Portal encryption is not configured.'),{status:503});const raw=Uint8Array.from(atob(env.FIELD_ENCRYPTION_KEY),x=>x.charCodeAt(0));if(raw.length!==32)throw Object.assign(Error('Portal encryption configuration is invalid.'),{status:503});return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}
async function encrypt(env,value){const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptoKey(env),new TextEncoder().encode(value));return `${b64(iv)}.${b64(new Uint8Array(data))}`;}
async function decrypt(env,value){const [iv,data]=value.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(atob(iv),x=>x.charCodeAt(0))},await cryptoKey(env),Uint8Array.from(atob(data),x=>x.charCodeAt(0))));}
async function device(request,env){const m=/^Bearer\s+(.+)$/i.exec(request.headers.get('Authorization')||'');if(!m)throw Object.assign(Error('A device key is required.'),{status:401});const row=await env.DB.prepare('SELECT d.*,l.status licence_status,f.name facility_name,w.name ward_name FROM devices d LEFT JOIN licences l ON l.id=d.licence_id JOIN facilities f ON f.id=d.facility_id JOIN wards w ON w.id=d.ward_id WHERE d.activation_token_hash=? LIMIT 1').bind(await digest(m[1])).first();if(!row)throw Object.assign(Error('Device access denied.'),{status:401});return row;}
async function cloudflare(env,path,options={}){if(!env.CF_ACCESS_API_TOKEN||!env.CF_ACCOUNT_ID)throw Object.assign(Error('Portal invitations are not configured yet.'),{status:503});const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}${path}`,{...options,headers:{Authorization:`Bearer ${env.CF_ACCESS_API_TOKEN}`,'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json();if(!response.ok||!data.success)throw Object.assign(Error(data.errors?.[0]?.message||'Cloudflare Access could not update the invitation.'),{status:502});return data.result;}
async function allowPortalEmail(env,email){const apps=await cloudflare(env,'/access/apps?per_page=100');const app=apps.find(x=>x.domain===env.PORTAL_HOST);if(!app)throw Object.assign(Error('The portal Access application could not be found.'),{status:503});const policies=await cloudflare(env,`/access/apps/${app.id}/policies?per_page=100`),normalised=email.toLowerCase(),existing=policies.find(policy=>policy.decision==='allow'&&policy.include?.some(rule=>rule.email?.email?.toLowerCase()===normalised));if(existing)return existing.id;const precedence=Math.max(0,...policies.map(x=>Number(x.precedence)||0))+1;const created=await cloudflare(env,`/access/apps/${app.id}/policies`,{method:'POST',body:JSON.stringify({name:`TESS portal invitation: ${email}`,decision:'allow',include:[{email:{email}}],precedence})});return created.id;}
async function sendMail(env,{to,subject,text:body,idempotencyKey}){if(!env.RESEND_API_KEY||!env.PORTAL_INVITE_FROM)return false;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':idempotencyKey},body:JSON.stringify({from:env.PORTAL_INVITE_FROM,to:[to],subject,text:body}),signal:AbortSignal.timeout(10000)});if(!response.ok)return false;return Boolean((await response.json()).id);}
async function sendInvitation(env,{email,facilityName,role,userId,attemptId='initial'}){const portalUrl=`https://${env.PORTAL_HOST}`;return sendMail(env,{to:email,subject:`You have been invited to the ${facilityName} TESS Facility Portal`,idempotencyKey:`tess-portal-invite-v3/${userId}/${attemptId}`,text:`Hello,\n\nYou have been granted ${role.replaceAll('_',' ')} access to the TESS Facility Portal for ${facilityName}.\n\nOpen the secure portal:\n${portalUrl}\n\nEnter this approved email address (${email}) and TruSelv will send your six-digit sign-in code.\n\nIf you were not expecting this invitation, please contact support@truselv.co.uk.\n\nTruSelv`});}
const ticketReference=()=>`TESS-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,4).toUpperCase()}`;
async function requestLogin(request,env){sameOrigin(request);const email=text((await input(request)).email,254)?.toLowerCase(),challengeId=id(),ipHash=await digest(request.headers.get('CF-Connecting-IP')||'unknown'),generic=()=>json({challengeId,message:'If this email has active portal access, a sign-in code has been sent.'});if(!email||!/^\S+@\S+\.\S+$/.test(email))return generic();const user=await env.DB.prepare(`SELECT u.id,u.email,f.name facility_name FROM facility_users u JOIN facilities f ON f.id=u.facility_id WHERE u.email=? AND u.active=1 AND f.status='active' AND u.role!='truselv_admin' LIMIT 1`).bind(email).first();if(!user)return generic();const [byUser,byIp]=await Promise.all([env.DB.prepare("SELECT COUNT(*) count FROM portal_login_challenges WHERE user_id=? AND created_at>=datetime('now','-15 minutes')").bind(user.id).first(),env.DB.prepare("SELECT COUNT(*) count FROM portal_login_challenges WHERE request_ip_hash=? AND created_at>=datetime('now','-15 minutes')").bind(ipHash).first()]);if(Number(byUser.count)>=5||Number(byIp.count)>=20)return generic();const code=String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0'),expiresAt=new Date(Date.now()+600000).toISOString(),codeHash=await authDigest(env,`${challengeId}.${code}`);await env.DB.prepare('INSERT INTO portal_login_challenges (id,user_id,code_hash,request_ip_hash,expires_at) VALUES (?,?,?,?,?)').bind(challengeId,user.id,codeHash,ipHash,expiresAt).run();const sent=await sendMail(env,{to:user.email,subject:'Your TruSelv sign-in code',idempotencyKey:`tess-login-code/${challengeId}`,text:`Your TruSelv sign-in code is:\n\n${code}\n\nIt expires in 10 minutes and can be used once.\n\nFacility: ${user.facility_name}\nPortal: https://${env.PORTAL_HOST}\n\nIf you did not request this code, you can ignore this email.\n\nTruSelv`});if(!sent)throw Object.assign(Error('We could not send the sign-in email. Please try again shortly.'),{status:502});return generic();}
async function verifyLogin(request,env){sameOrigin(request);const v=await input(request),challengeId=text(v.challengeId,64),code=text(v.code,6);if(!challengeId||!/^\d{6}$/.test(code||''))return fail('Enter the six-digit code from your email.',400);const challenge=await env.DB.prepare(`SELECT c.id,c.user_id,c.code_hash,c.attempts,c.expires_at,c.used_at,u.active,f.status facility_status FROM portal_login_challenges c JOIN facility_users u ON u.id=c.user_id JOIN facilities f ON f.id=u.facility_id WHERE c.id=? LIMIT 1`).bind(challengeId).first();if(!challenge||challenge.used_at||challenge.attempts>=5||challenge.expires_at<=now()||!challenge.active||challenge.facility_status!=='active')return fail('This code is invalid or has expired. Request a new code.',401);await env.DB.prepare('UPDATE portal_login_challenges SET attempts=attempts+1 WHERE id=?').bind(challengeId).run();if(!await secureEqual(challenge.code_hash,await authDigest(env,`${challengeId}.${code}`)))return fail('This code is incorrect. Please try again.',401);const token=b64(crypto.getRandomValues(new Uint8Array(32))),sessionId=id(),expiresAt=new Date(Date.now()+43200000).toISOString();await env.DB.batch([env.DB.prepare('UPDATE portal_login_challenges SET used_at=? WHERE id=?').bind(now(),challengeId),env.DB.prepare('INSERT INTO portal_sessions (id,user_id,token_hash,expires_at) VALUES (?,?,?,?)').bind(sessionId,challenge.user_id,await digest(token),expiresAt),env.DB.prepare('DELETE FROM portal_sessions WHERE expires_at<=?').bind(now())]);return new Response(JSON.stringify({ok:true}),{headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Set-Cookie':sessionCookie(token),'X-Content-Type-Options':'nosniff'}});}
async function dashboard(env,facilityId,wardId,seeResidents){
 const where=wardId?'facility_id=? AND ward_id=?':'facility_id=?',args=wardId?[facilityId,wardId]:[facilityId];
 const sessionWhere=wardId?'s.facility_id=? AND s.ward_id=?':'s.facility_id=?';
 const [dev,lic,events,features,people,sessions,residentActivity]=await Promise.all([
  env.DB.prepare(`SELECT COUNT(*) count FROM devices WHERE ${where} AND status='active'`).bind(...args).first(),
  env.DB.prepare("SELECT COUNT(*) count FROM licences WHERE facility_id=? AND status='active'").bind(facilityId).first(),
  env.DB.prepare(`SELECT COUNT(*) count FROM usage_events WHERE ${where} AND occurred_at>=datetime('now','-30 days')`).bind(...args).first(),
  env.DB.prepare(`SELECT feature,COUNT(*) count FROM usage_events WHERE ${where} AND occurred_at>=datetime('now','-30 days') GROUP BY feature ORDER BY count DESC LIMIT 5`).bind(...args).all(),
  seeResidents?env.DB.prepare(`SELECT COUNT(*) count FROM residents WHERE ${where} AND active=1`).bind(...args).first():Promise.resolve(null),
  env.DB.prepare(`SELECT COUNT(*) count,SUM(CASE WHEN mode='individual' THEN 1 ELSE 0 END) individual_count,SUM(CASE WHEN mode='group' THEN 1 ELSE 0 END) group_count,SUM(CASE WHEN anonymous=1 THEN 1 ELSE 0 END) anonymous_count FROM activity_sessions s WHERE ${sessionWhere} AND started_at>=datetime('now','-30 days')`).bind(...args).first(),
  seeResidents?env.DB.prepare(`SELECT r.id,r.first_name_cipher,r.last_name_cipher,COUNT(DISTINCT s.id) session_count FROM activity_sessions s JOIN activity_session_residents sr ON sr.session_id=s.id JOIN residents r ON r.id=sr.resident_id WHERE ${sessionWhere} AND s.started_at>=datetime('now','-30 days') GROUP BY r.id ORDER BY session_count DESC LIMIT 10`).bind(...args).all():Promise.resolve({results:[]})
 ]);
 const residentUsage=await Promise.all(residentActivity.results.map(async r=>({id:r.id,name:`${await decrypt(env,r.first_name_cipher)} ${await decrypt(env,r.last_name_cipher)}`.trim(),sessions:r.session_count})));
 return {activeDevices:dev.count,activeLicences:lic.count,interactions30d:events.count,featureUsage:features.results,residents:people?.count??null,sessions30d:Number(sessions.count)||0,individualSessions:Number(sessions.individual_count)||0,groupSessions:Number(sessions.group_count)||0,anonymousSessions:Number(sessions.anonymous_count)||0,residentUsage};
}
async function api(request,env,url){
 if(!env.DB)return fail('Database binding is not configured.',503);
 if(url.hostname===env.PORTAL_HOST&&url.pathname==='/api/auth/request'&&request.method==='POST')return requestLogin(request,env);
 if(url.hostname===env.PORTAL_HOST&&url.pathname==='/api/auth/verify'&&request.method==='POST')return verifyLogin(request,env);
 if(url.hostname===env.PORTAL_HOST&&url.pathname==='/api/auth/logout'&&request.method==='GET'){const token=cookie(request,'tess_portal_session');if(token)await env.DB.prepare('DELETE FROM portal_sessions WHERE token_hash=?').bind(await digest(token)).run();return new Response(null,{status:303,headers:{Location:'/', 'Set-Cookie':expiredSessionCookie,'Cache-Control':'no-store'}});}
 if(url.pathname==='/api/device/bootstrap'&&request.method==='GET'){const d=await device(request,env);await env.DB.prepare('UPDATE devices SET last_seen_at=? WHERE id=?').bind(now(),d.id).run();return json({deviceId:d.id,facilityId:d.facility_id,facilityName:d.facility_name,wardId:d.ward_id,wardName:d.ward_name,status:d.status,licenceStatus:d.licence_status||'missing',enabled:d.status==='active'&&d.licence_status==='active'});}
 if(url.pathname==='/api/device/activate'&&request.method==='POST'){const d=await device(request,env);if(['retired','suspended'].includes(d.status)||d.licence_status!=='active')return fail('This device cannot be activated.',403);await env.DB.prepare("UPDATE devices SET status='active',last_seen_at=? WHERE id=?").bind(now(),d.id).run();return json({deviceId:d.id,status:'active'});}
 if(url.pathname==='/api/device/context'&&request.method==='GET'){const d=await device(request,env);if(d.status!=='active'||d.licence_status!=='active')return fail('This device is not active.',403);const rows=(await env.DB.prepare('SELECT id,first_name_cipher,last_name_cipher FROM residents WHERE facility_id=? AND ward_id=? AND active=1 ORDER BY created_at').bind(d.facility_id,d.ward_id).all()).results,residentRows=await Promise.all(rows.map(async r=>({id:r.id,name:`${await decrypt(env,r.first_name_cipher)} ${await decrypt(env,r.last_name_cipher)}`.trim()}))),active=await env.DB.prepare("SELECT id,mode,anonymous,started_at FROM activity_sessions WHERE device_id=? AND status='active' ORDER BY started_at DESC LIMIT 1").bind(d.id).first();let participantIds=[];if(active)participantIds=(await env.DB.prepare('SELECT resident_id FROM activity_session_residents WHERE session_id=?').bind(active.id).all()).results.map(x=>x.resident_id);return json({residents:residentRows,activeSession:active?{id:active.id,mode:active.mode,anonymous:Boolean(active.anonymous),startedAt:active.started_at,residentIds:participantIds}:null});}
 if(url.pathname==='/api/device/sessions/start'&&request.method==='POST'){const d=await device(request,env);if(d.status!=='active'||d.licence_status!=='active')return fail('This device is not active.',403);const v=await input(request),mode=text(v.mode,20),requested=Array.isArray(v.residentIds)?[...new Set(v.residentIds.filter(x=>typeof x==='string'))]:[];if(!['individual','group'].includes(mode))return fail('Choose an individual or group session.');const available=(await env.DB.prepare('SELECT id FROM residents WHERE facility_id=? AND ward_id=? AND active=1').bind(d.facility_id,d.ward_id).all()).results.map(x=>x.id),availableSet=new Set(available),anonymous=available.length===0;if(!anonymous&&mode==='individual'&&requested.length!==1)return fail('Choose one resident for an individual session.');if(!anonymous&&mode==='group'&&requested.length<2)return fail('Choose at least two residents for a group session.');if(requested.some(x=>!availableSet.has(x)))return fail('One or more selected residents are unavailable.');const sessionId=id(),startedAt=now(),writes=[env.DB.prepare("UPDATE activity_sessions SET status='ended',ended_at=? WHERE device_id=? AND status='active'").bind(startedAt,d.id),env.DB.prepare('INSERT INTO activity_sessions (id,facility_id,device_id,ward_id,mode,anonymous,started_at) VALUES (?,?,?,?,?,?,?)').bind(sessionId,d.facility_id,d.id,d.ward_id,mode,anonymous?1:0,startedAt),...requested.map(residentId=>env.DB.prepare('INSERT INTO activity_session_residents (session_id,resident_id) VALUES (?,?)').bind(sessionId,residentId))];await env.DB.batch(writes);return json({id:sessionId,mode,anonymous,startedAt,residentIds:requested},201);}
 if(url.pathname==='/api/device/sessions/end'&&request.method==='POST'){const d=await device(request,env),v=await input(request),sessionId=text(v.sessionId,64);if(!sessionId)return fail('Choose an active session.');const result=await env.DB.prepare("UPDATE activity_sessions SET status='ended',ended_at=? WHERE id=? AND device_id=? AND status='active'").bind(now(),sessionId,d.id).run();if(!result.meta.changes)return fail('This session is no longer active.',409);return json({id:sessionId,status:'ended'});}
 if(url.pathname==='/api/device/events'&&request.method==='POST'){const d=await device(request,env);if(d.status!=='active'||d.licence_status!=='active')return fail('This device is not active.',403);if(!d.ward_id)return fail('This device must be assigned to a ward.',403);const events=(await input(request)).events;if(!Array.isArray(events)||!events.length||events.length>100)return fail('Send between 1 and 100 events.');const writes=[];for(const e of events){if(!/^[a-zA-Z0-9-]{16,64}$/.test(e.id||'')||!text(e.feature,80)||!text(e.eventName,80)||!Number.isFinite(Number(e.durationSeconds))||Number(e.durationSeconds)<0||Number(e.durationSeconds)>86400||Number.isNaN(Date.parse(e.occurredAt)))return fail('One or more usage events are invalid.');if(e.sessionId){const session=await env.DB.prepare("SELECT id FROM activity_sessions WHERE id=? AND device_id=? AND status='active'").bind(e.sessionId,d.id).first();if(!session)return fail('A usage event references an inactive session.');}writes.push(env.DB.prepare('INSERT OR IGNORE INTO usage_events (id,facility_id,device_id,ward_id,resident_id,session_id,feature,event_name,duration_seconds,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(e.id,d.facility_id,d.id,d.ward_id,null,e.sessionId||null,e.feature.trim(),e.eventName.trim(),Math.floor(Number(e.durationSeconds)),new Date(e.occurredAt).toISOString()));}await env.DB.batch(writes);await env.DB.prepare('UPDATE devices SET last_seen_at=? WHERE id=?').bind(now(),d.id).run();return json({accepted:events.length},202);}
 const user=await userFor(request,env);
 if(url.pathname==='/api/me'&&request.method==='GET')return json({email:user.email,role:user.role,facilityId:user.facility_id,facilityName:user.facility_name,wardId:user.ward_id,wardName:user.ward_name});
 if(url.pathname==='/api/admin/portal-auth-cutover'&&request.method==='POST'){sameOrigin(request);permitted(user,r=>r==='truselv_admin');const apps=await cloudflare(env,'/access/apps?per_page=100'),app=apps.find(x=>x.domain===env.PORTAL_HOST);if(!app)return fail('The portal Access application could not be found.',503);const policies=await cloudflare(env,`/access/apps/${app.id}/policies?per_page=100`),existing=policies.find(x=>x.name==='TruSelv facility sign-in'&&x.decision==='bypass');if(existing)return json({enabled:true,policyId:existing.id});const precedence=Math.max(0,...policies.map(x=>Number(x.precedence)||0))+1,policy=await cloudflare(env,`/access/apps/${app.id}/policies`,{method:'POST',body:JSON.stringify({name:'TruSelv facility sign-in',decision:'bypass',include:[{everyone:{}}],precedence})});await audit(env,user,'portal.authentication.enabled','access_policy',policy.id,{host:env.PORTAL_HOST});return json({enabled:true,policyId:policy.id});}
 if(url.pathname==='/api/admin/portfolio'&&request.method==='GET'){permitted(user,r=>r==='truselv_admin');const rows=await env.DB.prepare("SELECT f.id,f.name,f.status,f.created_at,(SELECT COUNT(*) FROM devices d WHERE d.facility_id=f.id AND d.status='active') active_devices,(SELECT COUNT(*) FROM licences l WHERE l.facility_id=f.id AND l.status='active') active_licences,(SELECT COUNT(*) FROM usage_events u WHERE u.facility_id=f.id AND u.occurred_at>=datetime('now','-30 days')) interactions_30d,(SELECT COUNT(*) FROM activity_sessions s WHERE s.facility_id=f.id AND s.started_at>=datetime('now','-30 days')) sessions_30d,(SELECT MAX(u.occurred_at) FROM usage_events u WHERE u.facility_id=f.id) last_activity_at FROM facilities f ORDER BY CASE f.status WHEN 'active' THEN 0 WHEN 'pending' THEN 1 ELSE 2 END, lower(f.name)").all();return json({facilities:rows.results});}
 if(url.pathname==='/api/facilities'&&request.method==='GET'){permitted(user,r=>r==='truselv_admin');return json({facilities:(await env.DB.prepare('SELECT id,name,status,created_at FROM facilities ORDER BY name').all()).results});}
 if(url.pathname==='/api/facilities'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const name=text((await input(request)).name,150);if(!name)return fail('A facility name is required.');const facilityId=id();await env.DB.prepare("INSERT INTO facilities (id,name,status) VALUES (?,?, 'pending')").bind(facilityId,name).run();await audit(env,user,'facility.created','facility',facilityId,{name});return json({id:facilityId,name,status:'pending'},201);}
 if(url.pathname==='/api/support/tickets'&&request.method==='GET'){const admin=user.role==='truselv_admin',wanted=url.searchParams.get('facilityId');if(!admin&&wanted&&wanted!==user.facility_id)return fail('Facility access denied.',403);const facilityFilter=admin?wanted:user.facility_id,where=facilityFilter?'WHERE t.facility_id=?':'',args=facilityFilter?[facilityFilter]:[];const tickets=(await env.DB.prepare(`SELECT t.*,f.name facility_name,(SELECT COUNT(*) FROM support_ticket_messages m WHERE m.ticket_id=t.id AND (m.visible_to_facility=1 OR ?=1)) message_count FROM support_tickets t JOIN facilities f ON f.id=t.facility_id ${where} ORDER BY CASE t.status WHEN 'new' THEN 0 WHEN 'open' THEN 1 WHEN 'waiting' THEN 2 WHEN 'resolved' THEN 3 ELSE 4 END,t.updated_at DESC LIMIT 500`).bind(admin?1:0,...args).all()).results;let messages=[];const ticketId=text(url.searchParams.get('ticketId'),64);if(ticketId){const ticket=tickets.find(x=>x.id===ticketId);if(!ticket)return fail('Ticket not found.',404);messages=(await env.DB.prepare(`SELECT id,author_email,author_role,message,visible_to_facility,created_at FROM support_ticket_messages WHERE ticket_id=?${admin?'':' AND visible_to_facility=1'} ORDER BY created_at`).bind(ticketId).all()).results;}return json({tickets,messages,categories:ticketCategories,statuses:ticketStatuses,priorities:ticketPriorities});}
 if(url.pathname==='/api/support/tickets'&&request.method==='POST'){const v=await input(request),category=text(v.category,40),subject=text(v.subject,150),description=text(v.description,5000),priority=ticketPriorities.includes(v.priority)?v.priority:'normal',facilityId=user.role==='truselv_admin'?text(v.facilityId,64):user.facility_id;if(!facilityId||!ticketCategories.includes(category)||!subject||!description)return fail('Choose a category and enter a subject and description.');const facility=await env.DB.prepare("SELECT id,name FROM facilities WHERE id=? AND status='active'").bind(facilityId).first();if(!facility)return fail('Choose an active facility.',400);const ticketId=id(),reference=ticketReference();await env.DB.prepare('INSERT INTO support_tickets (id,reference,facility_id,requester_user_id,requester_email,category,subject,description,priority) VALUES (?,?,?,?,?,?,?,?,?)').bind(ticketId,reference,facilityId,user.id,user.email,category,subject,description,priority).run();await audit(env,user,'support.ticket.created','support_ticket',ticketId,{reference,category,priority});const emailSent=await sendMail(env,{to:env.SUPPORT_INBOX||'support@truselv.co.uk',subject:`[${reference}] ${facility.name}: ${subject}`,idempotencyKey:`tess-support-new/${ticketId}`,text:`New TESS support request\n\nReference: ${reference}\nFacility: ${facility.name}\nFrom: ${user.email}\nCategory: ${category.replaceAll('-',' ')}\nPriority: ${priority}\n\n${description}\n\nManage this request at https://admin.truselv.co.uk`});return json({id:ticketId,reference,status:'new',emailSent},201);}
 if(url.pathname==='/api/support/tickets/update'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),ticketId=text(v.ticketId,64),status=text(v.status,20),priority=text(v.priority,20),assignedTo=text(v.assignedTo,254),resolution=typeof v.resolution==='string'?v.resolution.trim().slice(0,3000):'';if(!ticketId||!ticketStatuses.includes(status)||!ticketPriorities.includes(priority))return fail('Choose a valid ticket status and priority.');const ticket=await env.DB.prepare('SELECT t.*,f.name facility_name FROM support_tickets t JOIN facilities f ON f.id=t.facility_id WHERE t.id=?').bind(ticketId).first();if(!ticket)return fail('Ticket not found.',404);const resolvedAt=['resolved','closed'].includes(status)?(ticket.resolved_at||now()):null;await env.DB.prepare('UPDATE support_tickets SET status=?,priority=?,assigned_to=?,resolution=?,resolved_at=?,updated_at=? WHERE id=?').bind(status,priority,assignedTo||null,resolution||null,resolvedAt,now(),ticketId).run();await audit(env,user,'support.ticket.updated','support_ticket',ticketId,{status,priority,assignedTo:assignedTo||null});await sendMail(env,{to:ticket.requester_email,subject:`[${ticket.reference}] Support request updated`,idempotencyKey:`tess-support-update/${ticketId}/${id()}`,text:`Hello,\n\nYour TESS support request has been updated.\n\nReference: ${ticket.reference}\nFacility: ${ticket.facility_name}\nStatus: ${status}\nPriority: ${priority}${resolution?`\nResolution: ${resolution}`:''}\n\nYou can view the request at https://${env.PORTAL_HOST}\n\nTruSelv Support`});return json({id:ticketId,status,priority});}
 if(url.pathname==='/api/support/tickets/reply'&&request.method==='POST'){const v=await input(request),ticketId=text(v.ticketId,64),message=text(v.message,3000);if(!ticketId||!message)return fail('Enter a reply.');const ticket=await env.DB.prepare('SELECT t.*,f.name facility_name FROM support_tickets t JOIN facilities f ON f.id=t.facility_id WHERE t.id=?').bind(ticketId).first();if(!ticket||(user.role!=='truselv_admin'&&ticket.facility_id!==user.facility_id))return fail('Ticket not found.',404);const visible=user.role==='truselv_admin'?v.visibleToFacility!==false:true,nextStatus=user.role==='truselv_admin'?(visible?'waiting':ticket.status):'open';await env.DB.batch([env.DB.prepare('INSERT INTO support_ticket_messages (id,ticket_id,author_email,author_role,message,visible_to_facility) VALUES (?,?,?,?,?,?)').bind(id(),ticketId,user.email,user.role,message,visible?1:0),env.DB.prepare('UPDATE support_tickets SET status=?,updated_at=? WHERE id=?').bind(nextStatus,now(),ticketId)]);await audit(env,user,'support.ticket.replied','support_ticket',ticketId,{visibleToFacility:visible});if(visible){const recipient=user.role==='truselv_admin'?ticket.requester_email:(env.SUPPORT_INBOX||'support@truselv.co.uk');await sendMail(env,{to:recipient,subject:`[${ticket.reference}] New support reply`,idempotencyKey:`tess-support-reply/${ticketId}/${id()}`,text:`New reply for ${ticket.reference}\nFacility: ${ticket.facility_name}\nFrom: ${user.email}\n\n${message}\n\nView the request at ${user.role==='truselv_admin'?`https://${env.PORTAL_HOST}`:'https://admin.truselv.co.uk'}`});}return json({id:ticketId,status:nextStatus});}
 const facilityId=scope(user,url.searchParams.get('facilityId'));
 if(url.pathname==='/api/wards'&&request.method==='GET'){if(!facilityId)return fail('Choose a facility.',400);const own=user.role==='ward_analytics'?' AND id=?':'';const result=await env.DB.prepare(`SELECT id,name,active,created_at FROM wards WHERE facility_id=?${own} ORDER BY name`).bind(facilityId,...(own?[user.ward_id]:[])).all();return json({wards:result.results});}
 if(url.pathname==='/api/wards'&&request.method==='POST'){permitted(user,manage);const name=text((await input(request)).name,100);if(!facilityId||!name)return fail('A facility and ward name are required.');const wardId=id();await env.DB.prepare('INSERT INTO wards (id,facility_id,name) VALUES (?,?,?)').bind(wardId,facilityId,name).run();await audit(env,user,'ward.created','ward',wardId,{name});return json({id:wardId,name},201);}
 if(url.pathname==='/api/dashboard'&&request.method==='GET'){if(!facilityId)return fail('Choose a facility.',400);const w=await wardScope(env,user,facilityId,url.searchParams.get('wardId'));return json(await dashboard(env,facilityId,w?.id,residents(user.role)));}
 if(url.pathname==='/api/devices'&&request.method==='GET'){permitted(user,manage);if(!facilityId)return fail('Choose a facility.',400);const rows=await env.DB.prepare('SELECT d.id,d.label,d.platform,d.status,d.last_seen_at,d.app_version,d.licence_id,w.name ward_name,d.ward_id,d.created_at FROM devices d JOIN wards w ON w.id=d.ward_id WHERE d.facility_id=? ORDER BY d.created_at DESC').bind(facilityId).all();return json({devices:rows.results});}
 if(url.pathname==='/api/devices'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),label=text(v.label,100),licenceId=text(v.licenceId,64);if(!f||!label||!licenceId)return fail('Facility, ward, device label and licence are required.');const w=await ward(env,f,v.wardId,true),licence=await env.DB.prepare("SELECT id FROM licences WHERE id=? AND facility_id=? AND status='active'").bind(licenceId,f).first();if(!licence)return fail('Choose an active facility licence.');const deviceId=id(),key=b64(crypto.getRandomValues(new Uint8Array(32)));await env.DB.prepare('INSERT INTO devices (id,facility_id,ward_id,licence_id,label,activation_token_hash) VALUES (?,?,?,?,?,?)').bind(deviceId,f,w.id,licenceId,label,await digest(key)).run();await audit(env,user,'device.created','device',deviceId,{label,wardId:w.id});return json({id:deviceId,label,deviceKey:key,notice:'Copy this device key now. It cannot be viewed again.'},201);}
 if(url.pathname==='/api/licences'&&request.method==='GET'){permitted(user,manage);if(url.searchParams.get('all')==='1'){permitted(user,r=>r==='truselv_admin');return json({licences:(await env.DB.prepare('SELECT l.id,l.facility_id,f.name facility_name,l.status,l.seats,l.starts_on,l.ends_on,l.created_at FROM licences l JOIN facilities f ON f.id=l.facility_id ORDER BY l.created_at DESC').all()).results});}if(!facilityId)return fail('Choose a facility.',400);return json({licences:(await env.DB.prepare('SELECT id,facility_id,status,seats,starts_on,ends_on,created_at FROM licences WHERE facility_id=? ORDER BY created_at DESC').bind(facilityId).all()).results});}
 if(url.pathname==='/api/licences'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),f=text(v.facilityId,64),seats=Number(v.seats),starts=text(v.startsOn,10),ends=text(v.endsOn,10);if(!f||!Number.isInteger(seats)||seats<1||seats>10000||!/^\d{4}-\d{2}-\d{2}$/.test(starts||''))return fail('A facility, seat count and start date are required.');const licenceId=id();await env.DB.prepare('INSERT INTO licences (id,facility_id,seats,starts_on,ends_on) VALUES (?,?,?,?,?)').bind(licenceId,f,seats,starts,ends).run();await audit(env,user,'licence.created','licence',licenceId,{facilityId:f,seats});return json({id:licenceId},201);}
 if(url.pathname==='/api/licences/revoke'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),f=text(v.facilityId,64),licenceId=text(v.licenceId,64);if(!f||!licenceId)return fail('Choose a facility licence.',400);const licence=await env.DB.prepare('SELECT id,status FROM licences WHERE id=? AND facility_id=?').bind(licenceId,f).first();if(!licence)return fail('Licence not found.',404);if(licence.status!=='active')return fail('This licence is already inactive.',409);await env.DB.prepare("UPDATE licences SET status='suspended' WHERE id=?").bind(licenceId).run();await audit(env,user,'licence.revoked','licence',licenceId,{facilityId:f});return json({id:licenceId,status:'suspended'});}
 if(url.pathname==='/api/residents'&&request.method==='GET'){permitted(user,residents);if(!facilityId)return fail('Choose a facility.',400);const w=await wardScope(env,user,facilityId,url.searchParams.get('wardId'));const filter=w?' AND ward_id=?':'',rows=(await env.DB.prepare(`SELECT id,first_name_cipher,last_name_cipher,dob_cipher,active,created_at FROM residents WHERE facility_id=?${filter} ORDER BY created_at DESC`).bind(facilityId,...(w?[w.id]:[])).all()).results;return json({residents:await Promise.all(rows.map(async r=>({id:r.id,firstName:await decrypt(env,r.first_name_cipher),lastName:await decrypt(env,r.last_name_cipher),dateOfBirth:await decrypt(env,r.dob_cipher),active:Boolean(r.active),createdAt:r.created_at})))});}
 if(url.pathname==='/api/residents'&&request.method==='POST'){permitted(user,r=>r==='facility_admin');const v=await input(request),f=scope(user,v.facilityId),first=text(v.firstName,100),last=text(v.lastName,100),dob=text(v.dateOfBirth,10);if(!f||!first||!last||!/^\d{4}-\d{2}-\d{2}$/.test(dob||''))return fail('First name, last name and date of birth are required.');const w=await ward(env,f,v.wardId,true),residentId=id();await env.DB.prepare('INSERT INTO residents (id,facility_id,ward_id,first_name_cipher,last_name_cipher,dob_cipher) VALUES (?,?,?,?,?,?)').bind(residentId,f,w.id,await encrypt(env,first),await encrypt(env,last),await encrypt(env,dob)).run();await audit(env,user,'resident.created','resident',residentId);return json({id:residentId},201);}
 if(url.pathname==='/api/users'&&request.method==='GET'){permitted(user,manage);if(!facilityId)return fail('Choose a facility.',400);const rows=await env.DB.prepare('SELECT u.id,u.email,u.role,u.active,u.created_at,w.name ward_name,u.ward_id FROM facility_users u LEFT JOIN wards w ON w.id=u.ward_id WHERE u.facility_id=? ORDER BY u.email').bind(facilityId).all();return json({users:rows.results});}
 if(url.pathname==='/api/users'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase(),role=text(v.role,40);if(!f||!email||!/^\S+@\S+\.\S+$/.test(email)||!roles.includes(role)||role==='truselv_admin')return fail('A valid work email and facility role are required.');const w=role==='ward_analytics'?await ward(env,f,v.wardId,true):null,userId=id();await env.DB.prepare('INSERT INTO facility_users (id,facility_id,ward_id,email,role) VALUES (?,?,?,?,?)').bind(userId,f,w?.id||null,email,role).run();await audit(env,user,'user.provisioned','user',userId,{email,role,wardId:w?.id||null});return json({id:userId,email,role},201);}
 if(url.pathname==='/api/invitations'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase(),role=text(v.role,40);if(!f||!email||!/^\S+@\S+\.\S+$/.test(email)||!roles.includes(role)||role==='truselv_admin')return fail('A valid work email and facility role are required.');const w=role==='ward_analytics'?await ward(env,f,v.wardId,true):null;const facility=await env.DB.prepare('SELECT name FROM facilities WHERE id=? AND status=\'active\'').bind(f).first();if(!facility)return fail('Choose an active facility.',400);const exists=await env.DB.prepare('SELECT id FROM facility_users WHERE facility_id=? AND email=?').bind(f,email).first();if(exists)return fail('This email already has access for this facility.',409);const userId=id();await env.DB.prepare('INSERT INTO facility_users (id,facility_id,ward_id,email,role) VALUES (?,?,?,?,?)').bind(userId,f,w?.id||null,email,role).run();const emailSent=await sendInvitation(env,{email,facilityName:facility.name,role,userId});await audit(env,user,'user.invited','user',userId,{email,role,wardId:w?.id||null,emailSent});return json({id:userId,email,role,portalUrl:`https://${env.PORTAL_HOST}`,emailSent},201);}
 if(url.pathname==='/api/invitations/resend'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase();if(!f||!email)return fail('Choose an authorised email.',400);const facility=await env.DB.prepare('SELECT name FROM facilities WHERE id=? AND status=\'active\'').bind(f).first(),invited=await env.DB.prepare('SELECT id,email,role FROM facility_users WHERE facility_id=? AND email=? AND active=1').bind(f,email).first();if(!facility||!invited)return fail('This email does not have active portal access.',404);if(!await sendInvitation(env,{email:invited.email,facilityName:facility.name,role:invited.role,userId:invited.id,attemptId:id()}))return fail('The invitation email could not be accepted. Check the Resend sender configuration.',502);await audit(env,user,'user.invitation_resent','user',invited.id,{email});return json({email,portalUrl:`https://${env.PORTAL_HOST}`});}
 return fail('Not found.',404);
}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/')){try{if(!['GET','POST'].includes(request.method))return fail('Method not allowed.',405);if(request.method==='POST'&&!url.pathname.startsWith('/api/device/'))sameOrigin(request);return await api(request,env,url);}catch(e){return fail(e.message||'The request could not be completed.',e.status||500);}}return env.ASSETS.fetch(request);}};
