const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(error,status=400)=>json({error},status), id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const roles=['truselv_admin','facility_admin','facility_head','activities_lead','viewer','ward_analytics'];
const manage=r=>['truselv_admin','facility_admin'].includes(r), residents=r=>['truselv_admin','facility_admin','activities_lead'].includes(r);
const text=(v,max)=>typeof v==='string'&&v.trim()&&v.trim().length<=max?v.trim():null;
const b64=b=>btoa(String.fromCharCode(...b));
async function digest(v){return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))));}
async function input(request){if(Number(request.headers.get('content-length')||0)>65536)throw Object.assign(Error('Request is too large.'),{status:413});try{return await request.json();}catch{throw Object.assign(Error('Invalid JSON body.'),{status:400});}}
function permitted(user,test){if(!test(user.role))throw Object.assign(Error('You do not have permission for this action.'),{status:403});}
function scope(user,wanted){if(user.role==='truselv_admin')return wanted;if(!user.facility_id||(wanted&&wanted!==user.facility_id))throw Object.assign(Error('Facility access denied.'),{status:403});return user.facility_id;}
async function userFor(request,env){const email=(request.headers.get(env.ACCESS_HEADER||'Cf-Access-Authenticated-User-Email')||env.DEV_IDENTITY_EMAIL||'').trim().toLowerCase();if(!email)throw Object.assign(Error('Sign in is required.'),{status:401});const user=await env.DB.prepare(`SELECT u.id,u.facility_id,u.ward_id,u.email,u.role,u.active,f.name facility_name,f.status facility_status,w.name ward_name FROM facility_users u LEFT JOIN facilities f ON f.id=u.facility_id LEFT JOIN wards w ON w.id=u.ward_id WHERE u.email=? AND u.active=1 LIMIT 1`).bind(email).first();if(!user||(user.facility_id&&user.facility_status!=='active'))throw Object.assign(Error('Your account does not have active portal access.'),{status:403});return user;}
async function ward(env,facilityId,wardId,required=false){if(!wardId){if(required)throw Object.assign(Error('Choose a ward.'),{status:400});return null;}const row=await env.DB.prepare('SELECT id,name FROM wards WHERE id=? AND facility_id=? AND active=1').bind(wardId,facilityId).first();if(!row)throw Object.assign(Error('Ward access denied.'),{status:403});return row;}
async function wardScope(env,user,facilityId,wanted,required=false){const selected=user.role==='ward_analytics'?user.ward_id:(wanted||null);if(user.role==='ward_analytics'&&wanted&&wanted!==user.ward_id)throw Object.assign(Error('Ward access denied.'),{status:403});return ward(env,facilityId,selected,required);}
async function audit(env,user,action,type,target,details={}){await env.DB.prepare('INSERT INTO audit_log (id,facility_id,actor_email,action,target_type,target_id,details_json) VALUES (?,?,?,?,?,?,?)').bind(id(),user.facility_id||null,user.email,action,type,target,JSON.stringify(details)).run();}
async function cryptoKey(env){if(!env.FIELD_ENCRYPTION_KEY)throw Object.assign(Error('Portal encryption is not configured.'),{status:503});const raw=Uint8Array.from(atob(env.FIELD_ENCRYPTION_KEY),x=>x.charCodeAt(0));if(raw.length!==32)throw Object.assign(Error('Portal encryption configuration is invalid.'),{status:503});return crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']);}
async function encrypt(env,value){const iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptoKey(env),new TextEncoder().encode(value));return `${b64(iv)}.${b64(new Uint8Array(data))}`;}
async function decrypt(env,value){const [iv,data]=value.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(atob(iv),x=>x.charCodeAt(0))},await cryptoKey(env),Uint8Array.from(atob(data),x=>x.charCodeAt(0))));}
async function device(request,env){const m=/^Bearer\s+(.+)$/i.exec(request.headers.get('Authorization')||'');if(!m)throw Object.assign(Error('A device key is required.'),{status:401});const row=await env.DB.prepare('SELECT d.*,l.status licence_status,f.name facility_name,w.name ward_name FROM devices d LEFT JOIN licences l ON l.id=d.licence_id JOIN facilities f ON f.id=d.facility_id JOIN wards w ON w.id=d.ward_id WHERE d.activation_token_hash=? LIMIT 1').bind(await digest(m[1])).first();if(!row)throw Object.assign(Error('Device access denied.'),{status:401});return row;}
async function cloudflare(env,path,options={}){if(!env.CF_ACCESS_API_TOKEN||!env.CF_ACCOUNT_ID)throw Object.assign(Error('Portal invitations are not configured yet.'),{status:503});const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}${path}`,{...options,headers:{Authorization:`Bearer ${env.CF_ACCESS_API_TOKEN}`,'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json();if(!response.ok||!data.success)throw Object.assign(Error(data.errors?.[0]?.message||'Cloudflare Access could not update the invitation.'),{status:502});return data.result;}
async function allowPortalEmail(env,email){const apps=await cloudflare(env,'/access/apps?per_page=100');const app=apps.find(x=>x.domain===env.PORTAL_HOST);if(!app)throw Object.assign(Error('The portal Access application could not be found.'),{status:503});const policies=await cloudflare(env,`/access/apps/${app.id}/policies?per_page=100`);const precedence=Math.max(0,...policies.map(x=>Number(x.precedence)||0))+1;const created=await cloudflare(env,`/access/apps/${app.id}/policies`,{method:'POST',body:JSON.stringify({name:`TESS portal invitation: ${email}`,decision:'allow',include:[{email:{email}}],precedence})});return created.id;}
async function sendInvitation(env,{email,facilityName,role,userId}){if(!env.RESEND_API_KEY||!env.PORTAL_INVITE_FROM)return false;const portalUrl=`https://${env.PORTAL_HOST}`;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':`tess-portal-invite-v1/${userId}`},body:JSON.stringify({from:env.PORTAL_INVITE_FROM,to:[email],subject:`You have been invited to the ${facilityName} TESS Facility Portal`,text:`Hello,\n\nYou have been granted ${role.replaceAll('_',' ')} access to the TESS Facility Portal for ${facilityName}.\n\nOpen the secure portal:\n${portalUrl}\n\nEnter this work email address (${email}) and we will send you a one-time sign-in code.\n\nIf you were not expecting this invitation, please contact support@truselv.co.uk.\n\nTruSelv`}),signal:AbortSignal.timeout(10000)});if(!response.ok)return false;const data=await response.json();return Boolean(data.id);}
async function dashboard(env,facilityId,wardId,seeResidents){
 const where=wardId?'facility_id=? AND ward_id=?':'facility_id=?',args=wardId?[facilityId,wardId]:[facilityId];
 const [dev,lic,events,features,people]=await Promise.all([
  env.DB.prepare(`SELECT COUNT(*) count FROM devices WHERE ${where} AND status='active'`).bind(...args).first(),
  env.DB.prepare("SELECT COUNT(*) count FROM licences WHERE facility_id=? AND status='active'").bind(facilityId).first(),
  env.DB.prepare(`SELECT COUNT(*) count FROM usage_events WHERE ${where} AND occurred_at>=datetime('now','-30 days')`).bind(...args).first(),
  env.DB.prepare(`SELECT feature,COUNT(*) count FROM usage_events WHERE ${where} AND occurred_at>=datetime('now','-30 days') GROUP BY feature ORDER BY count DESC LIMIT 5`).bind(...args).all(),
  seeResidents?env.DB.prepare(`SELECT COUNT(*) count FROM residents WHERE ${where.replace('ward_id','ward_id')} AND active=1`).bind(...args).first():Promise.resolve(null)
 ]);
 return {activeDevices:dev.count,activeLicences:lic.count,interactions30d:events.count,featureUsage:features.results,residents:people?.count??null};
}
async function api(request,env,url){
 if(!env.DB)return fail('Database binding is not configured.',503);
 if(url.pathname==='/api/device/bootstrap'&&request.method==='GET'){const d=await device(request,env);await env.DB.prepare('UPDATE devices SET last_seen_at=? WHERE id=?').bind(now(),d.id).run();return json({deviceId:d.id,facilityId:d.facility_id,facilityName:d.facility_name,wardId:d.ward_id,wardName:d.ward_name,status:d.status,licenceStatus:d.licence_status||'missing',enabled:d.status==='active'&&d.licence_status==='active'});}
 if(url.pathname==='/api/device/activate'&&request.method==='POST'){const d=await device(request,env);if(['retired','suspended'].includes(d.status)||d.licence_status!=='active')return fail('This device cannot be activated.',403);await env.DB.prepare("UPDATE devices SET status='active',last_seen_at=? WHERE id=?").bind(now(),d.id).run();return json({deviceId:d.id,status:'active'});}
 if(url.pathname==='/api/device/events'&&request.method==='POST'){const d=await device(request,env);if(d.status!=='active'||d.licence_status!=='active')return fail('This device is not active.',403);if(!d.ward_id)return fail('This device must be assigned to a ward.',403);const events=(await input(request)).events;if(!Array.isArray(events)||!events.length||events.length>100)return fail('Send between 1 and 100 events.');const writes=[];for(const e of events){if(!/^[a-zA-Z0-9-]{16,64}$/.test(e.id||'')||!text(e.feature,80)||!text(e.eventName,80)||!Number.isFinite(Number(e.durationSeconds))||Number(e.durationSeconds)<0||Number(e.durationSeconds)>86400||Number.isNaN(Date.parse(e.occurredAt)))return fail('One or more usage events are invalid.');if(e.residentId){const r=await env.DB.prepare('SELECT id FROM residents WHERE id=? AND facility_id=? AND ward_id=? AND active=1').bind(e.residentId,d.facility_id,d.ward_id).first();if(!r)return fail('A usage event references an invalid resident.');}writes.push(env.DB.prepare('INSERT OR IGNORE INTO usage_events (id,facility_id,device_id,ward_id,resident_id,feature,event_name,duration_seconds,occurred_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(e.id,d.facility_id,d.id,d.ward_id,e.residentId||null,e.feature.trim(),e.eventName.trim(),Math.floor(Number(e.durationSeconds)),new Date(e.occurredAt).toISOString()));}await env.DB.batch(writes);await env.DB.prepare('UPDATE devices SET last_seen_at=? WHERE id=?').bind(now(),d.id).run();return json({accepted:events.length},202);}
 const user=await userFor(request,env);
 if(url.pathname==='/api/me'&&request.method==='GET')return json({email:user.email,role:user.role,facilityId:user.facility_id,facilityName:user.facility_name,wardId:user.ward_id,wardName:user.ward_name});
 if(url.pathname==='/api/admin/portfolio'&&request.method==='GET'){permitted(user,r=>r==='truselv_admin');const rows=await env.DB.prepare("SELECT f.id,f.name,f.status,f.created_at,(SELECT COUNT(*) FROM devices d WHERE d.facility_id=f.id AND d.status='active') active_devices,(SELECT COUNT(*) FROM licences l WHERE l.facility_id=f.id AND l.status='active') active_licences,(SELECT COUNT(*) FROM usage_events u WHERE u.facility_id=f.id AND u.occurred_at>=datetime('now','-30 days')) interactions_30d,(SELECT MAX(u.occurred_at) FROM usage_events u WHERE u.facility_id=f.id) last_activity_at FROM facilities f ORDER BY CASE f.status WHEN 'active' THEN 0 WHEN 'pending' THEN 1 ELSE 2 END, lower(f.name)").all();return json({facilities:rows.results});}
 if(url.pathname==='/api/facilities'&&request.method==='GET'){permitted(user,r=>r==='truselv_admin');return json({facilities:(await env.DB.prepare('SELECT id,name,status,created_at FROM facilities ORDER BY name').all()).results});}
 if(url.pathname==='/api/facilities'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const name=text((await input(request)).name,150);if(!name)return fail('A facility name is required.');const facilityId=id();await env.DB.prepare("INSERT INTO facilities (id,name,status) VALUES (?,?, 'pending')").bind(facilityId,name).run();await audit(env,user,'facility.created','facility',facilityId,{name});return json({id:facilityId,name,status:'pending'},201);}
 const facilityId=scope(user,url.searchParams.get('facilityId'));
 if(url.pathname==='/api/wards'&&request.method==='GET'){if(!facilityId)return fail('Choose a facility.',400);const own=user.role==='ward_analytics'?' AND id=?':'';const result=await env.DB.prepare(`SELECT id,name,active,created_at FROM wards WHERE facility_id=?${own} ORDER BY name`).bind(facilityId,...(own?[user.ward_id]:[])).all();return json({wards:result.results});}
 if(url.pathname==='/api/wards'&&request.method==='POST'){permitted(user,manage);const name=text((await input(request)).name,100);if(!facilityId||!name)return fail('A facility and ward name are required.');const wardId=id();await env.DB.prepare('INSERT INTO wards (id,facility_id,name) VALUES (?,?,?)').bind(wardId,facilityId,name).run();await audit(env,user,'ward.created','ward',wardId,{name});return json({id:wardId,name},201);}
 if(url.pathname==='/api/dashboard'&&request.method==='GET'){if(!facilityId)return fail('Choose a facility.',400);const w=await wardScope(env,user,facilityId,url.searchParams.get('wardId'));return json(await dashboard(env,facilityId,w?.id,residents(user.role)));}
 if(url.pathname==='/api/devices'&&request.method==='GET'){permitted(user,manage);if(!facilityId)return fail('Choose a facility.',400);const rows=await env.DB.prepare('SELECT d.id,d.label,d.platform,d.status,d.last_seen_at,d.app_version,d.licence_id,w.name ward_name,d.ward_id,d.created_at FROM devices d JOIN wards w ON w.id=d.ward_id WHERE d.facility_id=? ORDER BY d.created_at DESC').bind(facilityId).all();return json({devices:rows.results});}
 if(url.pathname==='/api/devices'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),label=text(v.label,100),licenceId=text(v.licenceId,64);if(!f||!label||!licenceId)return fail('Facility, ward, device label and licence are required.');const w=await ward(env,f,v.wardId,true),licence=await env.DB.prepare("SELECT id FROM licences WHERE id=? AND facility_id=? AND status='active'").bind(licenceId,f).first();if(!licence)return fail('Choose an active facility licence.');const deviceId=id(),key=b64(crypto.getRandomValues(new Uint8Array(32)));await env.DB.prepare('INSERT INTO devices (id,facility_id,ward_id,licence_id,label,activation_token_hash) VALUES (?,?,?,?,?,?)').bind(deviceId,f,w.id,licenceId,label,await digest(key)).run();await audit(env,user,'device.created','device',deviceId,{label,wardId:w.id});return json({id:deviceId,label,deviceKey:key,notice:'Copy this device key now. It cannot be viewed again.'},201);}
 if(url.pathname==='/api/licences'&&request.method==='GET'){permitted(user,manage);if(url.searchParams.get('all')==='1'){permitted(user,r=>r==='truselv_admin');return json({licences:(await env.DB.prepare('SELECT l.id,l.facility_id,f.name facility_name,l.status,l.seats,l.starts_on,l.ends_on,l.created_at FROM licences l JOIN facilities f ON f.id=l.facility_id ORDER BY l.created_at DESC').all()).results});}if(!facilityId)return fail('Choose a facility.',400);return json({licences:(await env.DB.prepare('SELECT id,facility_id,status,seats,starts_on,ends_on,created_at FROM licences WHERE facility_id=? ORDER BY created_at DESC').bind(facilityId).all()).results});}
 if(url.pathname==='/api/licences'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),f=text(v.facilityId,64),seats=Number(v.seats),starts=text(v.startsOn,10),ends=text(v.endsOn,10);if(!f||!Number.isInteger(seats)||seats<1||seats>10000||!/^\d{4}-\d{2}-\d{2}$/.test(starts||''))return fail('A facility, seat count and start date are required.');const licenceId=id();await env.DB.prepare('INSERT INTO licences (id,facility_id,seats,starts_on,ends_on) VALUES (?,?,?,?,?)').bind(licenceId,f,seats,starts,ends).run();await audit(env,user,'licence.created','licence',licenceId,{facilityId:f,seats});return json({id:licenceId},201);}
 if(url.pathname==='/api/licences/revoke'&&request.method==='POST'){permitted(user,r=>r==='truselv_admin');const v=await input(request),f=text(v.facilityId,64),licenceId=text(v.licenceId,64);if(!f||!licenceId)return fail('Choose a facility licence.',400);const licence=await env.DB.prepare('SELECT id,status FROM licences WHERE id=? AND facility_id=?').bind(licenceId,f).first();if(!licence)return fail('Licence not found.',404);if(licence.status!=='active')return fail('This licence is already inactive.',409);await env.DB.prepare("UPDATE licences SET status='suspended' WHERE id=?").bind(licenceId).run();await audit(env,user,'licence.revoked','licence',licenceId,{facilityId:f});return json({id:licenceId,status:'suspended'});}
 if(url.pathname==='/api/residents'&&request.method==='GET'){permitted(user,residents);if(!facilityId)return fail('Choose a facility.',400);const w=await wardScope(env,user,facilityId,url.searchParams.get('wardId'));const filter=w?' AND ward_id=?':'',rows=(await env.DB.prepare(`SELECT id,first_name_cipher,last_name_cipher,dob_cipher,active,created_at FROM residents WHERE facility_id=?${filter} ORDER BY created_at DESC`).bind(facilityId,...(w?[w.id]:[])).all()).results;return json({residents:await Promise.all(rows.map(async r=>({id:r.id,firstName:await decrypt(env,r.first_name_cipher),lastName:await decrypt(env,r.last_name_cipher),dateOfBirth:await decrypt(env,r.dob_cipher),active:Boolean(r.active),createdAt:r.created_at})))});}
 if(url.pathname==='/api/residents'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),first=text(v.firstName,100),last=text(v.lastName,100),dob=text(v.dateOfBirth,10);if(!f||!first||!last||!/^\d{4}-\d{2}-\d{2}$/.test(dob||''))return fail('First name, last name and date of birth are required.');const w=await ward(env,f,v.wardId,false),residentId=id();await env.DB.prepare('INSERT INTO residents (id,facility_id,ward_id,first_name_cipher,last_name_cipher,dob_cipher) VALUES (?,?,?,?,?,?)').bind(residentId,f,w?.id||null,await encrypt(env,first),await encrypt(env,last),await encrypt(env,dob)).run();await audit(env,user,'resident.created','resident',residentId);return json({id:residentId},201);}
 if(url.pathname==='/api/users'&&request.method==='GET'){permitted(user,manage);if(!facilityId)return fail('Choose a facility.',400);const rows=await env.DB.prepare('SELECT u.id,u.email,u.role,u.active,u.created_at,w.name ward_name,u.ward_id FROM facility_users u LEFT JOIN wards w ON w.id=u.ward_id WHERE u.facility_id=? ORDER BY u.email').bind(facilityId).all();return json({users:rows.results});}
 if(url.pathname==='/api/users'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase(),role=text(v.role,40);if(!f||!email||!/^\S+@\S+\.\S+$/.test(email)||!roles.includes(role)||role==='truselv_admin')return fail('A valid work email and facility role are required.');const w=role==='ward_analytics'?await ward(env,f,v.wardId,true):null,userId=id();await env.DB.prepare('INSERT INTO facility_users (id,facility_id,ward_id,email,role) VALUES (?,?,?,?,?)').bind(userId,f,w?.id||null,email,role).run();await audit(env,user,'user.provisioned','user',userId,{email,role,wardId:w?.id||null});return json({id:userId,email,role},201);}
 if(url.pathname==='/api/invitations'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase(),role=text(v.role,40);if(!f||!email||!/^\S+@\S+\.\S+$/.test(email)||!roles.includes(role)||role==='truselv_admin')return fail('A valid work email and facility role are required.');const w=role==='ward_analytics'?await ward(env,f,v.wardId,true):null;const facility=await env.DB.prepare('SELECT name FROM facilities WHERE id=? AND status=\'active\'').bind(f).first();if(!facility)return fail('Choose an active facility.',400);const exists=await env.DB.prepare('SELECT id FROM facility_users WHERE facility_id=? AND email=?').bind(f,email).first();if(exists)return fail('This email already has access for this facility.',409);const accessPolicyId=await allowPortalEmail(env,email);const userId=id();try{await env.DB.prepare('INSERT INTO facility_users (id,facility_id,ward_id,email,role,access_policy_id) VALUES (?,?,?,?,?,?)').bind(userId,f,w?.id||null,email,role,accessPolicyId).run();}catch(error){throw Object.assign(Error('The portal invitation could not be saved. Remove the new Cloudflare Access policy before retrying.'),{status:500});}const emailSent=await sendInvitation(env,{email,facilityName:facility.name,role,userId});await audit(env,user,'user.invited','user',userId,{email,role,wardId:w?.id||null,accessPolicyId,emailSent});return json({id:userId,email,role,portalUrl:`https://${env.PORTAL_HOST}`,emailSent},201);}
 if(url.pathname==='/api/invitations/resend'&&request.method==='POST'){permitted(user,manage);const v=await input(request),f=scope(user,v.facilityId),email=text(v.email,254)?.toLowerCase();if(!f||!email)return fail('Choose an authorised email.',400);const facility=await env.DB.prepare('SELECT name FROM facilities WHERE id=? AND status=\'active\'').bind(f).first(),invited=await env.DB.prepare('SELECT id,email,role FROM facility_users WHERE facility_id=? AND email=? AND active=1').bind(f,email).first();if(!facility||!invited)return fail('This email does not have active portal access.',404);if(!await sendInvitation(env,{email:invited.email,facilityName:facility.name,role:invited.role,userId:invited.id}))return fail('The invitation email could not be accepted. Check the Resend sender configuration.',502);await audit(env,user,'user.invitation_resent','user',invited.id,{email});return json({email,portalUrl:`https://${env.PORTAL_HOST}`});}
 return fail('Not found.',404);
}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/')){try{if(!['GET','POST'].includes(request.method))return fail('Method not allowed.',405);return await api(request,env,url);}catch(e){return fail(e.message||'The request could not be completed.',e.status||500);}}return env.ASSETS.fetch(request);}};
